### ISSUE TITLE
Stepper does not alpha rename

### ISSUE THREAD

**Issue by shriram** [racket/racket#2733] opened 2019-07-09 20:51 UTC
Here's my program:
```
(define x_0 5)

(let ([x 3])
  (+ x_0 x))
```
This output is not good.

![image](https://user-images.githubusercontent.com/75030/60921971-05f43880-a29c-11e9-9aac-bb6aeb8f494b.png)

**Comment by lexi-lambda** [comment] 2019-07-09 20:54
I think this might be a duplicate of #1936, though it’s doesn’t use `local`, so it’s not immediately clear to me if it’s the same root cause (or if it’s included in John’s “known” comment).

**Comment by jbclements** [comment] 2019-07-09 20:57
I'm guessing you're running this an older version of DrRacket (per my earlier suggestion)? I believe this bug is fixed in recent versions. Here's a screenshot from version 7.3:

<img width="523" alt="Screen Shot 2019-07-09 at 22 55 40" src="https://user-images.githubusercontent.com/226617/60922351-cb3ed000-a29c-11e9-98bb-bc406868cb6f.png">

I'm going to close this one. Let me know if that's a mistake.

**Closed by jbclements** 2019-07-09 20:57 UTC
