### ISSUE TITLE
`struct/c` exposes an internal error for contracted struct types with contracted parents

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#2623] opened 2019-04-24 06:53 UTC
The use of `struct/c` in following program raises a syntax error in terms of `struct/dc`, `provide/contract-id-source-start`, and `provide/contract-struct-expandsion-info-id-source`:
```racket
#lang racket
(module xml racket
  (struct source (start stop) #:transparent)
  (struct p-i source (target-name instruction) #:transparent)
  (provide (contract-out
            [struct source ([start any/c]
                            [stop any/c])]
            [struct (p-i source) ([start any/c]
                                  [stop any/c]
                                  [target-name symbol?]
                                  [instruction string?])])))
(require 'xml)

(struct/c p-i
          any/c any/c
          'xml "version=\"1.0\" encoding=\"utf-8\"")
```
`../../Applications/Racket v7.2/collects/racket/contract/private/struct-dc.rkt:1576:27: struct/dc: expected an identifier that names a field or a sequence with a field name, the #:parent keyword, and the parent struct in: (provide/contract-id-source-start #:parent provide/contract-struct-expandsion-info-id-source)`

This example is simplified from using `(require xml)` for the real `xml` library.

The error doesn't occur if the `provide` form is changed to either:
```racket
(provide (struct-out source)
         (contract-out
          [struct (p-i source) ([start any/c]
                                [stop any/c]
                                [target-name symbol?]
                                [instruction string?])]))
```
or:
```racket
(provide (struct-out p-i)
         (contract-out
          [struct source ([start any/c]
                          [stop any/c])]))
```
suggesting that the issue is related to both the child type and the parent type being protected with `contract-out` (or, actually, `provide/contract`).

**Comment by usaoc** [comment] 2023-08-17 10:16
Cannot reproduce this bug anymore.  Was it also fixed by ee773b2?  In any case, I think this issue can be closed.

**Closed** 2023-08-17 10:32 UTC
