### ISSUE TITLE
Error with require

### ISSUE THREAD

**Issue by zaoqi** [racket/racket#2103] opened 2018-05-26 13:01 UTC
rec.rkt can run.
`(require "rec.rkt")`
```
compiled/drracket/errortrace/rec_rkt.zo::4950: read (compiled): ill-formed code [../../../racket/gc2/../src/read.c:4905]
```

**Comment by pmatos** [comment] 2018-06-20 07:09
And what's `rec.rkt`?

**Comment by zaoqi** [comment] 2018-06-20 09:44
@pmatos 
It may be
```racket
  {provide define-rec}
  {define-syntax-rule {define-rec is? (f p ...)}
    {begin
      {define s (string->symbol (string-append "rec:" (symbol->string 'f)))}
      {define (f p ...) `#(,s ,p ...)}
      {define (is? x) (and (vector? x) (< 0 (vector-length x)) (eq? (vector-ref x 0) s))}
      {hel is? 1 (p ...)}}}
  {define-syntax hel
    {syntax-rules ()
      [(_ is? n (p)) {define (p x) (if (is? x) (vector-ref x n) (error))}]
      [(_ is? n (p . ps))
       {begin
         {define (p x) (if (is? x) (vector-ref x n) (error))}
         {define n2 (+ n 1)}
         {hel is? n2 ps}}]}}
```

**Comment by sorawee** [comment] 2020-04-22 20:21
I cannot reproduce the problem as well. @zaoqi, do you still have this problem? If not, I propose to close the issue.

**Closed** 2020-04-24 11:45 UTC
