### ISSUE TITLE
Insufficient/misleading intro documentation 

### ISSUE THREAD

**Issue by bigos** [racket/racket#2631] opened 2019-04-28 20:13 UTC
In the intro section
1.4 A Note to Readers with Lisp/Scheme Experience
https://docs.racket-lang.org/guide/intro.html

You give an example that makes no sense to me.

I have tried something similar and I could not make it work at all.

```
#lang racket

(define ns (make-base-namespace))

(define pie 3)

(define (booo)
  "booooooo")
```

repl output
```

Welcome to Racket v7.2.
racket@> (load "/home/jacek/raket-temporary.rktl")
racket@> pie
pie: undefined;
 cannot reference an identifier before its definition
  in module: top-level
  context...:
   eval-one-top12
   /usr/share/racket/collects/racket/repl.rkt:11:26
racket@> 
```

Where I can find documentation how I can solve this problem. I use Emacs with Geiser. I can press **f5** and achieve what I want but the documentation does not point to a place where I can find a reasonable explanation how to make it work and what is going on.

**Comment by samth** [comment] 2019-04-28 23:57
The problem is that the file you have there is a module, because it starts with #lang racket. That line is not there in the documentation example. 

That said, like the documentation, I recommend not using load and instead following the rest of the docs.

**Comment by bigos** [comment] 2019-04-29 05:27
I have removed `#lang racket` line and my scratchpad example works. I will try to  follow the rest of the docs.

**Comment by pmatos** [comment] 2019-07-25 07:43
Closing as the OPs issue seems to have been resolved.

**Closed by pmatos** 2019-07-25 07:43 UTC
