### ISSUE TITLE
Can't run in Windows 10 insider.

### ISSUE THREAD

**Issue by BearJean** [racket/racket#3010] opened 2020-01-20 09:42 UTC
Windows 10 Insider Preview Build 19041.21 （Slow）
I am not sure if the format is correct .

Dr.racket version :download from https://download.racket-lang.org/ racket-7.5-x86_64-win32.exe (78M)

before update the OS it just work fine.
but after that,whenever I open the Dr.Racket ,it just Stuck and I can't do anything ,even input a number,every Button no response,I have to kill it in Task Manage,

I have try to debug it with VS,just get a "Exception thrown: write access violation",I have ask someone if it is because my OS update .they recommanded me download the source ,build it,and find the bug.
what I find just a  s[0] = 0; 

in gmc.c 

 void scheme_gmp_tls_unload(intptr_t *s, void *data)
{
  current_total_allocation = (uintptr_t)s[0];
  max_total_allocation = (uintptr_t)s[1];
  gmp_tmp_current = (tmp_stack *)s[2];
  s[0] = 0;
  gmp_mem_pool = data;
}

in the Call Stack I jump to the position where the function be called.
just find :

static void done_with_GC () {
  scheme_gmp_tls_unload (XFORM_OK_ASSIGN (((Thread_Local_Variables * ) ((char * ) & scheme_thread_locals_space + scheme_tls_delta ) ) -> scheme_current_thread_ ) -> gmp_tls , XFORM_OK_ASSIGN (((Thread_Local_Variables * ) ((char * ) & scheme_thread_locals_space + scheme_tls_delta ) ) -> scheme_current_thread_ ) -> gmp_tls_data ) ; 
  XFORM_OK_ASSIGN (((Thread_Local_Variables * ) ((char * ) & scheme_thread_locals_space + scheme_tls_delta ) ) -> scheme_current_thread_ ) -> gmp_tls_data = ((void * ) 0 ) ; 
  if (XFORM_OK_ASSIGN (((Thread_Local_Variables * ) ((char * ) & scheme_thread_locals_space + scheme_tls_delta ) ) -> scheme_current_thread_ ) -> running ) {
    XFORM_OK_ASSIGN (((Thread_Local_Variables * ) ((char * ) & scheme_thread_locals_space + scheme_tls_delta ) ) -> scheme_current_runstack_ ) = XFORM_OK_ASSIGN (((Thread_Local_Variables * ) ((char * ) & scheme_thread_locals_space + scheme_tls_delta ) ) -> scheme_current_thread_ ) -> runstack ; 
    XFORM_OK_ASSIGN (((Thread_Local_Variables * ) ((char * ) & scheme_thread_locals_space + scheme_tls_delta ) ) -> scheme_current_runstack_start_ ) = XFORM_OK_ASSIGN (((Thread_Local_Variables * ) ((char * ) & scheme_thread_locals_space + scheme_tls_delta ) ) -> scheme_current_thread_ ) -> runstack_start ; 
  }
  scheme_resume_remembered_threads () ; 
  XFORM_OK_ASSIGN (((Thread_Local_Variables * ) ((char * ) & scheme_thread_locals_space + scheme_tls_delta ) ) -> end_this_gc_time_ ) = scheme_get_process_milliseconds () ; 
  XFORM_OK_ASSIGN (((Thread_Local_Variables * ) ((char * ) & scheme_thread_locals_space + scheme_tls_delta ) ) -> end_this_gc_real_time_ ) = scheme_get_inexact_milliseconds () ; 
  XFORM_OK_ASSIGN (((Thread_Local_Variables * ) ((char * ) & scheme_thread_locals_space + scheme_tls_delta ) ) -> scheme_total_gc_time_ ) += (XFORM_OK_ASSIGN (((Thread_Local_Variables * ) ((char * ) & scheme_thread_locals_space + scheme_tls_delta ) ) -> end_this_gc_time_ ) - XFORM_OK_ASSIGN (((Thread_Local_Variables * ) ((char * ) & scheme_thread_locals_space + scheme_tls_delta ) ) -> start_this_gc_time_ ) ) ; 
  XFORM_OK_ASSIGN (((Thread_Local_Variables * ) ((char * ) & scheme_thread_locals_space + scheme_tls_delta ) ) -> gc_prep_thread_chain_ ) = XFORM_OK_ASSIGN (((Thread_Local_Variables * ) ((char * ) & scheme_thread_locals_space + scheme_tls_delta ) ) -> scheme_current_thread_ ) ; 
  XFORM_OK_ASSIGN (((Thread_Local_Variables * ) ((char * ) & scheme_thread_locals_space + scheme_tls_delta ) ) -> scheme_current_thread_ ) -> gc_prep_chain = XFORM_OK_ASSIGN (((Thread_Local_Variables * ) ((char * ) & scheme_thread_locals_space + scheme_tls_delta ) ) -> scheme_current_thread_ ) ; 
  run_gc_callbacks (0 ) ; 
  scheme_future_continue_after_gc () ; 
}

I don't know what the "XFORM_OK_ASSIGN" is ,so I google it ,just find in 
https://github.com/racket/racket/blob/master/racket/collects/compiler/private/xform.rkt#L772

either I don't know what the file is.so my question is :
is my thinking right? and where can I find the doc about "what the file is".

and some else question ,in the case(I mean GUI Stuck),
I download the source from https://github.com/racket/racket and build it .
after I find it just a min part,not include the GUI,so what I find the "bug" 
whether or not really is the reason about GUI stuck?

I am not sure if this question is naive,I am new to it,so please give some tip at least  thanks!

**Comment by mflatt** [comment] 2020-01-26 13:55
Thanks for providing some debugging information. But that turns out to be an expected signal, because it implements a write barrier for the garbage collector.  In any case, I don't think that running in a debugger is going to help, because it sounds like the issue is at the GUI level, which is implemented in Racket.

Do you see the same behavior with the v7.6 pre-release candidate at http://pre-release.racket-lang.org/? If I remember correctly, v7.5 had a problem with input methods, and that should be fixed for the upcoming v7.6 release.

**Comment by BearJean** [comment] 2020-01-27 15:31
I down racket-7.5.0.900-x86_64-win32  and install it ,It work fine. thanks .

**Comment by BearJean** [comment] 2020-01-27 15:31
down -> download, sorry..

**Comment by mflatt** [comment] 2020-01-27 16:02
Great - thanks for checking the pre-release!

**Closed by mflatt** 2020-01-27 16:02 UTC

**Comment by BearJean** [comment] 2020-02-05 07:34
I'm sorry for the interruption agagin,but still some puzzled me.
I want to know the reason about the question above.

>because it sounds like the issue is at the GUI level, which is implemented in Racket.
>If I remember correctly, v7.5 had a problem with input methods, and that should be fixed for the upcoming v7.6 release.

I found what you said in https://github.com/racket/drracket/issues/331.
the question I still puzzled is ,why that would happen.
I find the src in https://github.com/racket/drracket
but not find the README as I except in https://github.com/racket/racket/blob/master/README.md.
which include a url tell me how to build the src .
in the build.md :

On Windows with Microsoft Visual Studio (any version between 2008/9.0 and 2019/16.0), nmake win32-in-place creates a build in the "racket" directory. For information on configuring your command-line environment for Visual Studio, see "racket/src/worksp/README.txt".

what I do is:
open the x64 Native Tools Command Prompt for VS 2019  and execute C:\Users\mingy\Desktop\racket-7.5.0.900\src\worksp\build.bat.

follow above I finish the build of racket.

I found this https://groups.google.com/forum/#!topic/racket-dev/B0VlRlX1LkQ

"The resultant DrRacket starts up fine and kind of works, but the UI locks up after a few keystrokes or mouse clicks."

that's the same as my condition ,rather just chinese input methods.
my env:  Windows 10 Insider Preview Build 19041.21 （Slow）
Dr.racket version :download from https://download.racket-lang.org/ racket-7.5-x86_64-win32.exe (78M)
before update the OS it just work fine.
but after update to this version,whenever I open the Dr.Racket ,it just Stuck and I can't do anything ,even input a number,every Button no response,I have to kill it in Task Manage

my question here is :how can I build the Drracket? can you please tell me how to build the Drracket,or give some url. I can't find it anywhere.
but find this https://groups.google.com/forum/#!searchin/racket-dev/Build$20Drracket|sort:date/racket-dev/kuGJ_Znww0Y/aVqqWwAEBwAJ
which say:
"I’m failing to build DrRacket on 10.14.6 with a recently updated XCode...""
so i think "to build Drracekt"may could todo.

**Comment by BearJean** [comment] 2020-02-05 07:55
I'm so sorry for that.
I have try it again, and find ,Every time I turn on the software for the first time 
Button can be pressed
When the input method is eng, the software works normally
Only after I change the input method to pinyin can the software get stuck
so I agree with you that"If I remember correctly, v7.5 had a problem with input methods",
so the request only one ,I want to know how to compile the Drracket and find the reason.
or if you can share whit about that bug..
sorry,because I need it to someone ,

When I first encountered this bug, I asked some people whether it was the operating system or the software itself. At last, they asked me to download the source code, compile and execute by myself, and find out the problematic code. And guess is not good, which is what a qualified programmer should do.

So I have to know why.

**Comment by soegaard** [comment] 2020-02-05 14:58
Den ons. 5. feb. 2020 kl. 08.55 skrev 223V <notifications@github.com>:

> so the request only one ,I want to know how to compile the Drracket and
> find the reason.
>

You can download precompiled binaries of the latest version on Github here:

    https://www.cs.utah.edu/plt/snapshots/

Note: It won't be long before 7.6 is released.

/Jens Axel
