### ISSUE TITLE
`read-bitmap` runs very slowly

### ISSUE THREAD

**Issue by bferris413** [racket/racket#3669] opened 2021-01-30 23:38 UTC
**What version of Racket are you using?**
Welcome to Racket v7.9 [bc].

**What program did you run?**
I'm writing a GUI CRUD app to learn Racket. Each item has an image associated with it, so I'm using `read-bitmap` to open the file and load the bitmap. Only one bitmap is loaded at a time, initiated by user-selection in a `list-box%`. Without drawing to any context, this operation takes ~5 seconds to load a 2-3MB jpeg. Why is it so slow? Is there a better way?

I figured I was doing something wrong in the application so I tried `read-bitmap` in DrRacket, which led to the same slowness:
```racket
#lang racket/gui
(require racket/draw)

(read-bitmap "/path/to/my.jpeg")
```

**What should have happened?**
The image should be read in a matter of milliseconds.

**If you got an error message, please include it here.**
No error messages.

**Please include any other relevant details**
Pop!_OS 20.10
Image size: 3024 × 4032 pixels

**Comment by samth** [comment] 2021-01-31 02:54
For a 2.5 MB JPG on my machine, I get 1.5 seconds to run that program, and about 600 ms when wrapping `time` around the call to `read-bitmap`. Which step were you measuring?

**Comment by sorawee** [comment] 2021-01-31 16:28
```
#lang racket/gui
(require racket/draw)

(read-bitmap "/path/to/my.jpeg")
```

will try to render the bitmap in the REPL. To measure cost due to `read-bitmap`, try:

```
(void (time (read-bitmap "/path/to/my.jpeg")))
```

**Comment by samth** [comment] 2021-01-31 16:37
That doesn't change the timing on my machine.

**Comment by bferris413** [comment] 2021-01-31 22:27
```racket
#lang racket/gui

(define example-frame (new frame% [label "Example"]))

(new button% (parent example-frame)
    (label "Read bitmap")
    (callback (lambda (button event)
                (print (time (read-bitmap "/my/jpeg.jpg"))))))
              
(send example-frame show #t)
```

`cpu time: 4273 real time: 4289 gc time: 111`

**Comment by shhyou** [comment] 2021-01-31 22:37
Could you check if the latest [snapshot build](https://snapshot.racket-lang.org/) has the same issue?

There was an issue related to Racket distribution compilation that will slow down some operations. I wonder is it is related here.
https://github.com/racket/drracket/issues/350#issuecomment-759123949
https://github.com/racket/racket/commit/c64bf5d96199885dc8ae49ba73742ea95bfbf662

**Comment by bferris413** [comment] 2021-02-09 13:20
> Could you check if the latest [snapshot build](https://snapshot.racket-lang.org/) has the same issue?

Yes, I'll do that shortly. Apologies for the delay, I haven't been able to get back to this yet.

**Comment by bferris413** [comment] 2021-02-13 00:48
I was able to download the latest snapshot build, the results are improved
`cpu time: 703 real time: 763 gc time: 28`

**Comment by sorawee** [comment] 2021-03-08 09:04
@bferris413 a few programs that really need bitmaps to load fast use https://docs.racket-lang.org/images/Embedding_Bitmaps_in_Compiled_Files.html to load the bitmaps at compile-time. That is, the compile-time will increase, but the run-time will decrease. This is useful when you distribute an executable (compiled) program to users. However, if you are still developing your program, you need to recompile the program, so it likely won't have any beneficial effect during the development.

In any case, since the issue is fixed, I will close it.

**Closed by sorawee** 2021-03-08 09:04 UTC
Labels: performance
