### ISSUE TITLE
The error message of `require`-ing a non-existent file is not helpful

### ISSUE THREAD

**Issue by edom** [racket/racket#2855] opened 2019-10-10 18:03 UTC
### Version

Racket 7.4 on Debian 9.

### How to reproduce

Save this in `a.rkt`.

```
#lang racket/base
(require b)
```

Run `racket -t a.rkt`.

The problem: The error message does not mention `a.rkt`.

### What is expected

The error message should also mention the path of the offending source (`a.rkt`).

**Comment by sorawee** [comment] 2020-04-22 23:41
Duplicate of #2680

**Closed by sorawee** 2020-04-22 23:41 UTC
