### ISSUE TITLE
[Feature Request] Use LaTeX generated labels in Plot package

### ISSUE THREAD

**Issue by encomer** [racket/racket#3321] opened 2020-07-30 19:14 UTC
In the plot package, when using labels, it is often desirable to write a mathematical expression or function. But the labels are string type. It would be great to use LaTeX generated labels for using in plots, as an alternative to strings, specially in the context of the _Scribble language_, with the **scribble-math** package.

The solution I know isn't easy, because labels in Plot are Strings.

For example, in the following code in DrRacket 7.7:
#lang scribble/manual
@require[plot
         scribble-math]
@title{Pro LaTeX labels in Plot}
@(plot
  (function
   (λ(x) (exp (- (* x x))))
   -2 2)
  #:title "y(x)=exp(-x^2)")
@(define title2 @${y(x)=\mathsf{e}^{-x^2}})
@title2

It would be nice, to just write:
  #:title (**latex-label** title2)

Thank you for the possibility of including in the future this capability in Plot. It would greatly increase its appealing for mathematical oriented scribble documents. _Also, thank you in advance for any suggestion about how to add LaTeX labels with a combination of current packages and capabilities._

_Please Keep Safe_.
E. Cómer

**Comment by soegaard** [comment] 2020-07-30 20:38
FWIW I don't think it's possible to use `scribble-math` in this scenario.
The intended use of `scribble-math` is to embed the Latex formula into 
an html-page which uses MathJax to render the formula at browse time.

Instead you can experiment with `latex-pict` which provides functions
that turns a LaTeX formula into a pict, which you can superimpose
on the plot. If `plot` supports picts as labels, then it is straightforward
to place the labels.

https://docs.racket-lang.org/latex-pict/index.html

**Comment by encomer** [comment] 2020-07-31 00:03
Thank you Jens Soegaard.
I try **latex-pict** but it seems that I'm having a problem with dependencies. _I will keep looking for a minimum example of translating LaTeX to Picts_. Any pointer concerning this is very welcome.

Once that is achieved, then as you said, because the **Plot** module, support functions like _point-pict_ , then the rest is (or should be) straightforward.

Thank you for your support, and also por all your previous work, particularly for the **Metapict** module.
Enrique Cómer

**Comment by alex-hhh** [comment] 2020-07-31 05:24
There is already a similar feature request in the racket/plot package (https://github.com/racket/plot/issues/58), and this issue should also be transferred there, or closed as a duplicate.

**Comment by sorawee** [comment] 2020-07-31 06:02
Close as duplicate of racket/plot#58

**Closed by sorawee** 2020-07-31 06:02 UTC
