### ISSUE TITLE
Release Regressions for 8.6

### ISSUE THREAD

**Issue by jbclements** [racket/racket#4366] opened 2022-07-19 11:55 UTC
Here are the current results for checking release regressions:

##### Package no longer exists

These all are, or depend on, packages whose source doesn't exist. 

- [x] 3d-model https://plt.cs.northwestern.edu/pkg-build/server/built/fail/3d-model.txt
- [x] alpaca https://plt.cs.northwestern.edu/pkg-build/server/built/fail/alpaca.txt
- [x] elf https://plt.cs.northwestern.edu/pkg-build/server/built/fail/elf.txt
- [x] quad https://plt.cs.northwestern.edu/pkg-build/server/built/fail/quad.txt
- [x] words https://plt.cs.northwestern.edu/pkg-build/server/built/fail/words.txt

(sent mail to all authors)

### Test Failures

These test failures are all caused by https://github.com/racket/rackunit/pull/158.

- [x] crypto-test https://plt.cs.northwestern.edu/pkg-build/server/built/test-fail/crypto-test.txt (marking as complete per Ryan's comment below)
- [x] gnucash https://plt.cs.northwestern.edu/pkg-build/server/built/test-fail/gnucash.txt (merged pull request)
- [x] gregor-test https://plt.cs.northwestern.edu/pkg-build/server/built/test-fail/gregor-test.txt
- [x] multiscope https://plt.cs.northwestern.edu/pkg-build/server/built/test-fail/multiscope.txt (merged pull request)
- [x] suffixtree https://plt.cs.northwestern.edu/pkg-build/server/built/test-fail/suffixtree.txt (merged pull request)
- [ ] unlike-assets-test https://plt.cs.northwestern.edu/pkg-build/server/built/test-fail/unlike-assets-test.txt

### Other Failures
- [x] plai-typed This only fails in the HEAD build, not the release build.
- [x] protobuf I think `protobuf` and `rival` both include a sample blog post with the same name.
- [x] typed-compose Timeout in the no-extra-dependencies VM; unlikely to be actually related to the package.

**Comment by mflatt** [comment] 2022-07-19 12:29
Many of the test failures appear to be due to a contract check added in racket/rackunit#158.

**Comment by sorawee** [comment] 2022-07-19 14:40
Yes, I opened PRs for those issues already (except two; see below).

- `crypto-test`: is it really a failure due to the the `rackunit` change? The log shows:
   ```
   raco test: (submod "/home/root//user/.local/share/racket/snapshot/pkgs/crypto-test/tests/test.rkt" test)
   test.rkt: racket test: timeout after 240 seconds
   ```
- `gnu-cash` and `suffix-tree`: https://github.com/jbclements/suffixtree/pull/1 and https://github.com/jbclements/gnucash/pull/2 (CC: @jbclements)
- `gregor-test`: https://github.com/97jaz/gregor/pull/53 (CC: @97jaz)
- `multiscope`: https://github.com/michaelballantyne/multiscope/pull/1 (CC: @michaelballantyne)
- `unlike-assets-test`: the version posted to the package server is unmaintained. The maintained version is in Denxi. See the discussion at https://github.com/racket/rackunit/pull/158#issuecomment-1168569212  (CC: @zyrolasting)

**Comment by jbclements** [comment] 2022-07-19 15:01
Holy mackerel, you guys are on it. I step away for a few hours and everything's taken care of. Thanks!

**Comment by jbclements** [comment] 2022-07-19 15:04
I do not think it makes sense to delay the changes to rackunit; the fixes are largely very straightforward, and I don't want to wait any longer to start testing, especially since a significant fraction of the builds are now failing because of gateway timeouts on the os x signing process. It might make sense to add code to retry on this kind of error message. (Assuming I'm understanding what's going on correctly.)

**Comment by jbclements** [comment] 2022-07-19 15:05
I'm also planning to send mail to those whose package sources no longer exist, some of them may be self-hosted. Matthew Butterick is one of these people, I will also send him mail.

**Comment by rfindler** [comment] 2022-07-19 15:07
If reverting just one commit somewhere on a release branch is what it would take to postpone this change until the next release, I'd be in favor of that. I know they've had some time to respond but I'm more comfortable with a little bit more time.

@sorawee I followed the pkg source issue. I assume that's one of the ones where there is no pending pull request. Is the other one `crypto-test`?

**Comment by sorawee** [comment] 2022-07-19 15:08
Yep, the other one is `crypto-test` (which I don't think is actually related to rackunit -- but I'm also testing locally to see if that's actually the case).

**Comment by jbclements** [comment] 2022-07-19 15:09
> @jbclements you might find the `--checkboxes` option to `pkg-build-diff` helpful.

Excellent, added this to the checklist template, many thanks.

**Comment by jbclements** [comment] 2022-07-19 15:47
I'm super-confused by the state of 

https://pkgs.racket-lang.org/package/unlike-assets-test

Specifically, the package catalog info appears to contain a reference to a broken URL (specifically, to a commit that does not exist in the github repo). So... why are all the builds succeeding? I guess it's possible that Sage just just changed that source pointer, but the "last updated" date for the package is "Wednesday, June 8th, 2022 8:53:11pm (UTC)"; I guess I don't really know whether that refers to the last date on which the catalog entry was altered or the date on which the repo it points to was updated.

All signs point to me misunderstanding something. Can someone help me understand what's going on here?

**Comment by samth** [comment] 2022-07-19 16:04
I believe that @zyrolasting has a complex setup for `unlike-assets` which he's in the process of moving to Denxi, his package management system. However, `unlike-assets-test` installs fine on my machine, which suggests that something is wrong in getting the checksum.

**Comment by samth** [comment] 2022-07-19 16:05
@rfindler it looks like all of those PRs have now been merged, so I don't think we need to postpone anything.

**Comment by sorawee** [comment] 2022-07-19 16:13
@samth 

When you install `unlike-assets-test`, you will get this message:

```
$ raco pkg install unlike-assets-test
Resolving "unlike-assets-test" via https://pkgs.racket-lang.org
Downloading repository https://github.com/zyrolasting/unlike-assets.git?path=unlike-assets-test#7fb08d6902d34399c96a325d6d27f1ff84813b commit 7fb08d6902d34399c96a325d68fd27f1ff84813b
The following uninstalled packages are listed as dependencies of unlike-assets-test:
   unlike-assets-lib
```

Note that `7fb08d6902d34399c96a325d6d27f1ff84813b` and `7fb08d6902d34399c96a325d68fd27f1ff84813b` are not the same. The right one is correct, and has `8f` in the middle. The left one doesn't.

`raco pkg install` uses `https://github.com/zyrolasting/unlike-assets.git?path=unlike-assets-test`. Ignore `#7fb08d69...`. And uses `commit 7fb08d690...`. So they all "work out".

I assume `pkg-build` does something similar to `raco pkg install`. That's why it's successful.

`pkg-index`, on the other hand, fully uses `https://github.com/zyrolasting/unlike-assets.git?path=unlike-assets-test#7fb08d6902d34399c96a325d6d27f1ff84813b`. So it fails.

Putting hashes here for comparison

```
7fb08d6902d34399c96a325d6d27f1ff84813b
7fb08d6902d34399c96a325d68fd27f1ff84813b
```

**Comment by sorawee** [comment] 2022-07-19 16:30
That's my understanding.

But note that this is a totally separate issue. In fact, fixing the commit hash will not fix the test failure. 
1. I can't submit a PR to fix a problem in a pinned git commit.
2. At some point, `unlike-assets-test` already sidesteps the problem by removing the problematic test.

I think perhaps the proper action here is @zyrolasting either (1) upgrades the pinned git commit to a version that doesn't have a problem or (2) entirely deletes `unlike-assets-test`.

**Comment by jbclements** [comment] 2022-07-20 15:20
But shouldn't we also open an issue for the bug that Sam identified in (3) above?

**Comment by jbclements** [comment] 2022-07-20 15:21
Also, per Sam's comment above (all merged), I'm checking the remainder of the boxes and closing this issue.

**Comment by samth** [comment] 2022-07-20 15:23
I don't think this is accurate. All the PRs have been merged but that does not resolve 100% of the issues.

**Comment by sorawee** [comment] 2022-07-20 15:37
> But shouldn't we also open an issue for the bug that Sam identified in (3) above?

#4368

**Comment by samth** [comment] 2022-07-31 19:34
Current status:

- A failure in aoc-racket that has now gone away
- A failure in cover-badge that does not reproduce for me locally
- A failure in crypto-test that might be due to different local libraries? (cc @rmculpepper)

**Comment by mfelleisen** [comment] 2022-10-11 09:01
I’d rather release with the extra check in place. ~~ As I remarked, I had to respond to one failure myself but it turned out that this was a genuine (non-crucial) bug in the code.

**Comment by jbclements** [comment] 2023-02-02 23:11
@samth, okay to close this? Are you waiting for action from @rmculpepper on this?

**Closed** 2023-02-03 00:17 UTC
