### ISSUE TITLE
Mac M1, minimal racket, read-line returns immediately, i.e. not reading at all

### ISSUE THREAD

**Issue by Inc0n** [racket/racket#4440] opened 2022-09-23 22:22 UTC
**What version of Racket are you using?**
8.6 [cs]

**What program did you run?**
Running this in any repl caused the problem.
```
(read-line)
```
Here are the results of trying all 5 different modes to no avail.
```
lambda.rkt> (read-line (current-input-port) 'any)
""
lambda.rkt> (read-line (current-input-port) 'any-one)
""
lambda.rkt> (read-line (current-input-port) 'linefeed)
""
lambda.rkt> (read-line (current-input-port) 'return)
my-string
; user break
lambda.rkt> (read-line (current-input-port) 'return-linefeed)
my-string-again
; user break
```

**What should have happened?**
`read-line` should wait for user input until `return` is hit, and return the line entered as a string.
Also `(read-line (current-input-port) 'any)` should work, i.e. works like describe above.

**Please include any other relevant details**
e.g., the operating system used or how you are running the code.
Mac M1 12.3
Emacs: 28.2

I encountered it whilst in racket-repl using Emacs, but running racket in the terminal exhibit the same behaviour.
As a result I decided, I should post the issue here, instead to the emacs package `racket-mode`.

**Additional information**

I am slightly puzzled to the results I have found on the internet, but here are some references:
https://www.reddit.com/r/Racket/comments/r62krw/please_fix_readline/
https://www.reddit.com/r/Racket/comments/nd3gz5/rackets_inherent_problem_readline/
https://steloflute.tistory.com/entry/Rackets-inherent-problem-read-line

**Comment by sorawee** [comment] 2022-09-23 23:17
Can you confirm that you really experience this issue in the command-line? While I can reproduce this problem in Racket Mode, I can't reproduce the problem in the command-line. 

```
$ racket                                                                                                                                                                                    
Welcome to Racket v8.6.0.12 [cs].
> (read-line)
abcdef
"abcdef"
```

(I also use Mac M1, Racket 8.6.)

Note that what you "found on the internet" is, in my understanding, a different issue. They are about the default mode to handle line separator.

**Comment by Inc0n** [comment] 2022-09-24 11:42
Unfortunately it doesn't work in CMD either. I tried in Terminal.app, here is what it looks like:
```
$ racket 
Welcome to Racket v8.6 [cs].
> (read-line)
""
> 
```
The rest of the modes behave exactly as I have listed prior.

**Comment by jbclements** [comment] 2022-09-24 19:40
1) This is not what I observe on my M1 mac using the Terminal app.
2) However, I can get something similar if I pipe input to racket:
```
Grossvogel:/tmp clements> cat /tmp/foo
(read-line)
abc
Grossvogel:/tmp clements> racket < /tmp/foo
Welcome to Racket v8.6.0.5 [cs].
> ""
> ; abc: undefined;
;  cannot reference an identifier before its definition
;   in module: top-level
; [,bt for context]
> 
```

This suggests to me that file i/o behaves differently in "interactive" vs "non-interactive" environments. It seems plausible to me that there are aspects of your shell setup that are triggering the "non-interactive" behavior.

This also seems like it could be related to the change in v8.4 to expeditor vs. readline. Take a look at those [release notes](https://blog.racket-lang.org/2022/02/racket-v8-4.html), and see whether the suggestion there affects your issue.

**Comment by Inc0n** [comment] 2022-09-25 09:54
Thanks! I had a look and the following seems relevant:
+ The first point: Command-line Racket provides a new expression editor by default for its read-eval-print loop (REPL). (Rest of the paragraph truncated)
+ Another point later on:
   > To turn off expeditor and make Racket’s REPL go back to the old editline/readline-based editor, use the command

   ```
   ,input readline
   ```
   I tried this, and my shell does not understand this.
   <details>
   <summary>Result in shell</summary>

  ```shell
  $ racket  
  Welcome to Racket v8.6 [cs].
  > ,input readline
  stdin::32: unquote: not in quasiquote
	in: (unquote input)
	location...:
	 stdin::32
	context...:
	 /opt/homebrew/Cellar/minimal-racket/8.6/share/racket/collects/racket/repl.rkt:11:26
  > readline: undefined;
   cannot reference an identifier before its definition
	in module: top-level
	context...:
	 body of top-level
	 /opt/homebrew/Cellar/minimal-racket/8.6/share/racket/collects/racket/repl.rkt:11:26
  > 
  ```
  </details>
	
+ Lastly, I had not mention that I installed `minimal-racket` instead of racket on brew. Which might be important?

**Comment by soegaard** [comment] 2022-09-25 12:26
On macOS I recommend using the official installer:

https://download.racket-lang.org/

(Click more installers to get to the minimal distribution)

**Comment by jbclements** [comment] 2022-09-25 15:17
I agree that it might be relevant that you're using minimal. In re the `,input readLine`... this is a command you supply to the Racket REPL, not at the command line. Or is that what you tried?

**Comment by sorawee** [comment] 2022-09-25 15:20
A couple of things:

- Even Minimal Racket from download.racket-lang.org won't come with expeditor.
- Is there a reason you don't want to install the full Racket? `brew install --cask racket` should have the functional expeditor.

**Comment by jbclements** [comment] 2022-09-25 15:34
Okay, I can now confirm that I see this behavior on minimal racket. 

Next question: is this a bug, or is this expected behavior for Racket Minimal?

**Comment by Inc0n** [comment] 2022-09-25 16:08
> I agree that it might be relevant that you're using minimal. In re the `,input readLine`... this is a command you supply to the Racket REPL, not at the command line. Or is that what you tried?

So if I understood you correctly, `,input readline` a command to be entered at the REPL, i.e. insides the prompts of the repl. And not at the command line, i.e. not as flags to be passed into `racket` executable.

If you want to see the results of my `,input readline` run inside the racket repl. Please refer back to my previous comment in the section relating to this matter, where there should be a collaspable `Result in shell` drawer, which contains the record of my execution.

>     * Is there a reason you don't want to install the full Racket? `brew install --cask racket` should have the functional expeditor.

Well, if I am not wrong, the full package would include a `drracket.app` which I would not use over Emacs, in that case, my preferance is `minimal-racket`. Unfortunately, that would means losing on some fairly convenient features also with `racket-mode`.

So, I should lastly mention that I have not had `drracket` installed as well......
i.e. had not ran `raco pkg install --auto drracket`.

**Comment by jbclements** [comment] 2022-09-25 16:29
As @sorawee pointed out, minimal racket does not include expeditor. So that ",input readLine" is not going to do anything useful, I believe.

It is probably possible to repair this by installing the expeditor package and possibly other related packages. I'm pretty confident that the *fast* way to repair it is just to install the full racket package. Which is more important: your time or your disk space?

(I should add that if this is a bug, and I think it might be, we should definitely fix it! I'm also focused on getting you a working installation, though.)

**Comment by sorawee** [comment] 2022-09-25 16:41
If I recall correctly, getting expeditor working also requires ncurses installed when compiling Racket from source (`brew install minimal-racket` compiles from source does under the hood). It's not just a matter of installing an extra package.

**Comment by capfredf** [comment] 2022-09-25 17:49
> Well, if I am not wrong, the full package would include a drracket.app which I would not use over Emacs, in that case, my preferance is minimal-racket. Unfortunately, that would means losing on some fairly convenient features also with racket-mode.

If you are going to use `racket-mode`, then I would recommend full-racket over minimal-racket [c.f. https://racket-mode.com/#Minimal-Racket]

**Comment by jbclements** [comment] 2022-09-25 20:56
I've just gone digging, and it appears to me that versions of minimal racket going back to 7.0 exhibit this behavior, so this is not something new (unless it's the Terminal that's changed...). I'm going to close this issue, because I think this is the expected behavior of racket. It would be nice to be able to refer you to an entry in the documentation, but I think it's entwined with various issues around the Terminal and interactive shells etc. etc., and I can't find anything relevant, alas. 

@mflatt , does this sound right to you?

**Closed by jbclements** 2022-09-25 20:56 UTC
