### ISSUE TITLE
Contracted elements in signatures not working (since at least Racket 6.4)

### ISSUE THREAD

**Issue by dfeltey** [racket/racket#1652] opened 2017-03-31 22:06 UTC
This program:

```
#lang racket

(module sig racket
  (provide contracted-toy-factory^)
  (define-signature contracted-toy-factory^
    (toy?
     (contracted
      [toy-color  (-> toy? symbol?)]))))

(module unit racket
  (require (submod ".." sig))
  (define-unit contracted-simple-factory@
    (import)
    (export contracted-toy-factory^)
    (define (toy-color n) 'red)
    (define (toy? n) #t)))
```

Runs in Racket 6.2, but in Racket 6.4+ gives the following error:
```
toy?: unbound identifier in module
  context...:
  other binding...:
  other binding...:
  other binding...:
  other binding...:
  other binding...: in: toy?
```

**Comment by dfeltey** [comment] 2017-03-31 22:31
Here's a slightly smaller example:

```
#lang racket

(module sig racket
  (provide true^)
  (define-signature true^
    ((contracted
      [true/c  true/c]))))

(module unit racket
  (require (submod ".." sig))
  (define-unit true@
    (import)
    (export true^)
    (define true/c #t)))
```

**Comment by LiberalArtist** [comment] 2018-07-21 10:31
This continues to be broken in both Racket 6.12 and Racket 6.90.0.901. Among other examples, it means that the code in [Adding Contracts to Signatures](http://docs.racket-lang.org/guide/Contracts_for_Units.html#%28part._.Adding_.Contracts_to_.Signatures%29) from the Racket Guide does not actually work.

The problem only seems to emerge when the signature and the unit are in different modules. This single-module variant of @dfeltey's last example does work:
```racket
#lang racket

(define-signature true^
  ((contracted
    [true/c  true/c])))

(define-unit true@
  (import)
  (export true^)
  (define true/c #t))
```

**Comment by LiberalArtist** [comment] 2018-07-21 10:46
It looks like this broke in Racket 6.3, which was the debut of "set of scopes" expander. I guess that means I should ping @mflatt.

**Comment by LiberalArtist** [comment] 2018-07-23 00:33
Thanks to the macro stepper, it looks like the fragment of syntax with the wrong scope comes from `ctc` in https://github.com/racket/racket/blob/e97717ef2b79ab3e1e852932f2673b3cc691382f/racket/collects/racket/unit.rkt#L966-L972

I haven't tracked down whether it's a missing scope or a superfluous scope, nor whether the bug is in the syntax packaged up by `define-signature` or the way it's used by `unit`. (I have not delved into the implementation of units at all before: I don't even consider myself an expert at _using_ units.)

I can say that the bug occurs with `unit`, not just `define-unit`:
```racket
#lang racket

(module sig racket
  (provide true^)
  (define-signature true^
    ((contracted
      [true/c true/c]))))

(require 'sig)

(define true@
  (unit (import)
        (export true^)
        (define true/c #t)))
```

Also, the problem isn't related to the same identifier appearing on the left-hand-side and right-hand-side of the `contracted` subform:
```racket
#lang racket

(module sig racket
  (provide thing^)
  (define-signature thing^
    (thing/c
     (contracted
      [thing thing/c]))))

(require 'sig)

(define thing@
  (unit (import)
        (export thing^)
        (define thing/c #t)
        (define thing #t)))
```

**Comment by LiberalArtist** [comment] 2018-07-23 00:37
A tangential thought: it would be nice if the functions created by e.g. `make-syntax-introducer` supported adding a symbol or something to the associated scope for debugging purposes, similarly to how module scopes are printed in error messages with the name of the module.

**Comment by LiberalArtist** [comment] 2018-07-23 01:32
With more thanks to the macro stepper, here is an interesting expansion step (with `configure-runtime` submodules elided for space):
```racket
(module true-single-file racket
  (#%module-begin
   (module sig racket
     (#%module-begin
      (#%provide true^)
      (define-values (signature-tag) (#%app gensym))
      (define-syntaxes (true^)
        (make-set!-transformer
         (make-signature
          (make-siginfo (list #'true^) (list (quote-syntax signature-tag)))
          (list (quote-syntax true/c)) ;; <1>
          (list)
          (list)
          (list)
          (list (quote-syntax true/c)) ;; <2>
          (quote-syntax true^))))
      (define-values ()
        (begin (lambda (true/c) (let-values () true/c (#%app void))) (#%app values)))))
   (#%require:18 'sig)
   (define-values:19 (true@)
     (make-unit:21
      'true@:21
      (vector-immutable:21)
      (vector-immutable:21 (cons:21 'true^:25 (vector-immutable:21 signature-tag)))
      (list:21)
      (syntax-parameterize:21
       ([current-contract-region:21
         (lambda:21 (stx:21) #'(quote:21 (unit:21 true@:21)))])
       (lambda:21 ()
         (let:21 ([temp1:42 (box:21 unsafe-undefined:21)])
           (values:21
            (lambda:21 (import-table:21)
              (let-values:21 ()
                (letrec-syntaxes:21 ()
                  (letrec-syntaxes+values:21 ()
                                             ()
                    (unit-body:21
                     (unit (import) (export true^) (define true/c #t)) ;; <3>
                     ()
                     (true/c) ;; <4>
                     (temp1:42)
                     ((contract:21 . true/c)) ;; <5>
                     (begin:21 (define true/c #t))))))) ;; <3>
            (unit-export:21
             ((signature-tag)
              (vector-immutable:21
               (λ:21 ()
                 (check-not-unsafe-undefined:21 (unbox:21 temp1:42) 'true/c)))))))))))))
```
I labeled potentially-relevant appearances of `true/c` in comments. Here is the information reported by the macro stepper—`<5>` the unbound one, and note that `<3> appears twice:

- `<1>`: line: 7; column: 7; position: 102; source module: this module; original?: `#f`
    - #(246757 module)
    - #(246764 module sig)
    - #(246778 macro)
- `<2>`: line: 7; column: 14; position: 109; source module: this module; original?: `#f`
    - #(246757 module)
    - #(246764 module sig)
    - #(246778 macro)
- `<3>`: line: 14, column: 16; position: 208, source module: this module; original?: `#t`
    - #(246739 module)
    - #(246746 module true-single-file)
    - #(246819 use-site)
- `<4>`: line: 7; column: 7; position: 102; source module: this module; original?: `#t`
    - #(246739 module)
    - #(246746 module true-single-file)
    - #(246819 use-site)
- `<5>`: line: 7; column: 14; position: 109; source module: this module; original?: `#f`
    - #(246757 module)
    - #(246764 module sig)
    - #(246778 macro)
    - #(246819 use-site)

**Comment by LiberalArtist** [comment] 2018-07-23 02:02
A few steps further on, `unit-body:21` expands to:
```racket
(block:49
                 (define-values:49 (true/c:50) #t)
                 (begin:49
                   (contract:49
                    true/c ;; <5*>
                    true/c:50
                    (current-contract-region:49)
                    'cant-happen:49
                    (quote:49 true/c)
                    (quote-srcloc:49 true/c)) ;; <3*>
                   (set-box!:49
                    temp1:42
                    (cons:49 true/c:50 (current-contract-region:49))))
                 (define-syntax:49 true/c ;; <3*>
                   (make-id-mapper:49 (quote-syntax:49 true/c:50))))
```

Here `<5*>` and `<3*>` are like `<5>` and `<3>`, but with a bunch of additional common scopes.

**Comment by LiberalArtist** [comment] 2018-07-23 02:39
My impression from all of that: it seems like `<5*>` should really be `<3*>`. `<5*>` comes from the right-hand side of the `contracted` subform of `define-signature`, whereas `<3*>` comes from `(define true/c #t)`. But I don't think it's just an issue of the wrong template: however uses of signature identifiers are supposed to be resolved to actual definitions provided from units, it seems like that isn't happening. 

The documentation for `define-signature` says that "variables in the contract expressions are treated the same as for `define-syntaxes`". It says the same thing about the right-hand sides of `define-values` and `define-values-for-export` subforms, but `define-values-for-export`, at least, doesn't seem to have this problem. The following program works and prints `1`:
```racket
#lang racket

(module sig racket
  (provide ^)
  (define-signature ^
    (x y
     (define-values-for-export (y)
       (add1 x)))))

(require 'sig)

(define-unit @
  (import)
  (export ^)
  (define x 0))

(define-values/invoke-unit/infer @)

y
```

**Comment by LiberalArtist** [comment] 2018-07-23 02:53
It looks like this is where the problematic part of `unit-body`'s expansion is built: https://github.com/racket/racket/blob/e97717ef2b79ab3e1e852932f2673b3cc691382f/racket/collects/racket/unit.rkt#L1183-L1193

**Comment by LiberalArtist** [comment] 2018-07-23 03:07
The value of `var-info-ctc` is populated here: https://github.com/racket/racket/blob/e97717ef2b79ab3e1e852932f2673b3cc691382f/racket/collects/racket/unit.rkt#L1136-L1152
where `localify` is: https://github.com/racket/racket/blob/e97717ef2b79ab3e1e852932f2673b3cc691382f/racket/collects/racket/unit.rkt#L883-L888

**Comment by LiberalArtist** [comment] 2018-07-23 04:33
I think the problem might be that the contract expressions don't ever seem to go through a transformation like this one: https://github.com/racket/racket/blob/e97717ef2b79ab3e1e852932f2673b3cc691382f/racket/collects/racket/unit.rkt#L603-L620

**Comment by LiberalArtist** [comment] 2018-07-23 04:56
Here's an example that reproduces the problem in a single module:
```racket
#lang racket

(define-signature true^
  ((contracted
    [true/c true/c])))

(let ()
  (unit (import)
        (export true^)
        (define true/c #t)))
```

**Comment by LiberalArtist** [comment] 2018-07-25 18:52
It looks like `unit/c` and `define-unit/contract` are not affected by this bug, only contracts in signatures:
```racket
#lang racket

(define-signature true^
  (true/c))

(let ()
  (unit/c
   (import)
   (export (true^ [true/c true/c]))))

(let ()
  (define-unit/contract true@
    (import)
    (export (true^ [true/c true/c]))
    (define true/c #t))
  true@)
```

**Comment by LiberalArtist** [comment] 2018-07-28 04:16
Trying to use `define-unit/contract` as a workaround is affected by https://github.com/racket/racket/issues/2196.

**Comment by lexi-lambda** [comment] 2018-10-16 21:55
I bumped into this today, so I just pushed a fix that seems to work. Thanks @LiberalArtist for the forensics! They were helpful.

**Closed** 2018-10-16 21:54 UTC
