### ISSUE TITLE
About DrRacket does not display text if background is dark

### ISSUE THREAD

**Issue by Sunspark-007** [racket/racket#4051] opened 2021-11-07 00:06 UTC
**What version of Racket are you using?**
8.3 [cs]

**What program did you run?**
n/a

**What should have happened?**
It should have displayed all the text that displays when the background is light.

**If you got an error message, please include it here.**
n/a

**Please include any other relevant details**
Windows 10
The text is present in the dialog box, clicking and dragging the mouse to select it will highlight some of it.
The fix for this would be to add a check, if background is <> #FFFFFF then make text color #FFFFFF.

**Comment by rfindler** [comment] 2021-11-07 02:50
Can you say a little bit more about which text? Perhaps share a screenshot?

Thanks,
Robby

**Comment by Sunspark-007** [comment] 2021-11-07 05:24
<img width="639" alt="racket_light" src="https://user-images.githubusercontent.com/73711243/140633472-eb6dc65e-4fdd-4321-983d-db50ed14769f.png">
<img width="639" alt="racket_dark" src="https://user-images.githubusercontent.com/73711243/140633485-7cf2e589-de0d-41b0-8ce6-e2b38b819e62.png">

**Comment by rfindler** [comment] 2021-11-30 21:48
This is a duplicate of racket/drracket#523 ; this one came in first, but that one is in the right repo, so I'll close this one.

**Closed by rfindler** 2021-11-30 21:48 UTC
