### ISSUE TITLE
raco pkg install: "call-with-file-lock/timeout: contract violation"

### ISSUE THREAD

**Issue by bensmrs** [racket/racket#4798] opened 2023-10-19 13:37 UTC
**What version of Racket are you using?**
8.4 to 8.10 BC, minimal

**What program did you run?**
`raco pkg install -i cext-lib`

**What should have happened?**
`cext-lib` should install

**If you got an error message, please include it here.**
```
call-with-file-lock/timeout: contract violation
  expected: (>=/c 0.0)
  given: '0.01
  context...:
   /xxx/8.10/share/racket/collects/racket/file.rkt:698:0: call-with-file-lock/timeout
   /xxx/8.10/share/racket/collects/pkg/main.rkt:223:16
   /xxx/8.10/share/racket/collects/racket/private/more-scheme.rkt:206:2: call-handled-body
```

**Please include any other relevant details**
I need Racket BC, so I compiled the minimal version (on macOS Ventura). When compiling the minimal version using CS with the same options, the command works as expected. (I’m really no expert of Racket, I’m just trying to repackage a legacy application, but) There seems to be a confusion in the default `delay` argument, where `0.01` gets interpreted as `'0.01`…

Hope that’s enough to reproduce!

**Comment by mflatt** [comment] 2023-10-20 17:03
Thanks for the report, but I haven't been able to replicate this, yet. It's a strange error; since numbers are self-quoting, `'0.01` is the same as `0.01`. So, something is confused about the representation of numbers or the printing of a non-number.

The steps I tried are: download the Minimal Racket source, configure with `--enable-bcdefault``make` and `make install`, and then `raco pkg install -i cext-lib` uses the in-place install. I'm on an M2 Mac running Ventura. Maybe there's some other ingredient I'm missing?

**Comment by bensmrs** [comment] 2023-10-20 21:42
Well… that’s a bummer.
You know what, I have a simpler way to reproduce the bug on my machine. Download https://download.racket-lang.org/releases/8.10/installers/racket-8.10-x86_64-macosx-bc.dmg, extract it.
```
#> /Applications/Racket\ v8.10/bin/raco pkg install -i cext-lib
call-with-file-lock/timeout: contract violation
  expected: (>=/c 0.0)
  given: '0.01
  context...:
   /Applications/Racket v8/collects/racket/file.rkt:698:0: call-with-file-lock/timeout
   /Applications/Racket v8/collects/pkg/main.rkt:223:16
   (submod "/Applications/Racket v8/collects/pkg/main.rkt" main): [running body]
   "/Applications/Racket v8/collects/raco/raco.rkt": [running body]
   "/Applications/Racket v8/collects/raco/main.rkt": [running body]
```

FWIW, I have a MacBook Pro (M1 Max) running on macOS 13.4.1.

**Comment by sorawee** [comment] 2023-10-20 21:48
The paths under `context` show `/Applications/Racket v8/`, which doesn't match the fresh installation path at `/Applications/Racket\ v8.10/`. Do you have a symlink or anything like that?

FWIW, I also can't reproduce the issue, even with https://download.racket-lang.org/releases/8.10/installers/racket-8.10-x86_64-macosx-bc.dmg.

```
$ /Applications/Racket\ v8.10/bin/raco pkg install -i cext-lib
Resolving "cext-lib" via https://download.racket-lang.org/releases/8.10/catalog/
Downloading https://download.racket-lang.org/releases/8.10/pkgs/cext-lib.zip
Promoting cext-lib from auto-installed to explicitly installed
```

I'm using Mac M2 running 13.5.2.

**Comment by bensmrs** [comment] 2023-10-20 21:53
Silly copy/paste mistake; I had moved it to `Racket v8` to test something. The (real this time!!) output is
```
call-with-file-lock/timeout: contract violation
  expected: (>=/c 0.0)
  given: '0.01
  context...:
   /Applications/Racket v8.10/collects/racket/file.rkt:698:0: call-with-file-lock/timeout
   /Applications/Racket v8.10/collects/pkg/main.rkt:223:16
   (submod "/Applications/Racket v8.10/collects/pkg/main.rkt" main): [running body]
   "/Applications/Racket v8.10/collects/raco/raco.rkt": [running body]
   "/Applications/Racket v8.10/collects/raco/main.rkt": [running body]
```

**Comment by mflatt** [comment] 2023-10-20 21:58
Do you have a `~/Library/Racket` directory? Does moving it away change how `raco pkg` behaves?

If not, I wonder similarly about `~/Library/Preferences/org.racket-lang.prefs.rktd`.

**Comment by bensmrs** [comment] 2023-10-20 22:01
I moved both and the result is the same. I’m installing a macOS VM to see if I can reproduce on a fresh macOS install.

**Comment by bensmrs** [comment] 2023-10-20 22:15
Just installed Ventura 13.5.2 on UTM. Downloaded the DMG, installed it, did `softwareupdate --install-rosetta`, then the command I did previously. Same problem.

**Comment by sorawee** [comment] 2023-10-20 22:23
Can you run this in the REPL of the Racket BC? What does it output?

```
(let ()
  (define delay 0.01)
  (unless (and (real? delay) (not (negative? delay)))
    (raise-argument-error 'call-with-file-lock/timeout "(>=/c 0.0)" delay))
  123)
```

**Comment by bensmrs** [comment] 2023-10-20 22:30
I’m actually very surprised:
<img width="632" alt="image" src="https://github.com/racket/racket/assets/25688414/afb13bb8-8a71-428d-a56a-7936346bbfbe">

**Comment by sorawee** [comment] 2023-10-20 22:36
Uhh, what is this...

Just to be clear, you typed `(let () (define delay 0.01)` and press enter, and that's the result?

Can you type `,bt` for the backtrace?

**Comment by bensmrs** [comment] 2023-10-20 22:40
Yep I did that (I double-checked on CS, to be extra sure, and obviously it worked). `,bt` gives:
```
append: contract violation
  expected: list?
  given: #<void>
  context...:
   /Applications/Racket v8.10/share/pkgs/xrepl-lib/xrepl/xrepl.rkt:1776:2: reader-loop
   /Applications/Racket v8.10/collects/racket/repl.rkt:11:26
```

**Comment by mflatt** [comment] 2023-10-20 22:45
I think this interaction confirms that something is deeply wrong, and the REPL's expeditor isn't able to work with inexact numbers, either.

**Comment by bensmrs** [comment] 2023-10-20 22:48
“Deeply wrong” is exactly what it felt 🙂. Replacing `0.01` with `0` works, as we could expect.

**Comment by bensmrs** [comment] 2023-10-20 22:57
I just checked on previous versions and it works on 7.9 BC, but stops working from 8.0 BC.

**Comment by mflatt** [comment] 2023-10-20 22:59
What if you start racket with `-j` (which disables the JIT)?

**Comment by bensmrs** [comment] 2023-10-20 23:02
Disabling the JIT does nothing…

**Comment by bensmrs** [comment] 2023-10-20 23:04
I’ll `git bisect`. That’ll probably take me some time but that should help.

**Comment by sorawee** [comment] 2023-10-20 23:07
Just curious. What does each of these evaluate to?

- `(expt 3 2)`
- `(expt 3.0 2)`
- `(expt (exact->inexact 3) 2)`

**Comment by bensmrs** [comment] 2023-10-20 23:09
```
> (expt 3 2)
9
> (expt 3.0 2)
expt: contract violation
  expected: number?
  given: '10.0
  argument position: 1st
  other arguments...:
   1
append: contract violation
  expected: list?
  given: #<void>
 [,bt for context]
> (expt (exact->inexact 3) 2)
9.0
```

**Comment by sorawee** [comment] 2023-10-20 23:13
Looks like a problem with the reader. That `10.0` is probably from https://github.com/racket/racket/blob/master/racket/src/expander/read/number.rkt#L256

**Closed** 2024-07-29 00:36 UTC
Labels: bug, unexplained, platform:macos
