### ISSUE TITLE
Crashes when attempting to construct (unquote [value]) 

### ISSUE THREAD

**Issue by blevenson** [racket/racket#2847] opened 2019-10-04 02:20 UTC
It is impossible to construct (unquote 4) without causing Dr. Racket to crash.  Running `(list 'unquote 4)` causes the program to hang.

**Comment by jackfirth** [comment] 2019-10-04 06:18
Could you share more details about how you're evaluating `(list 'unquote 4)`? I'm unable to reproduce this in any of these environments:

- DrRacket 7.4 definitions area
- DrRacket 7.4 REPL
- Racket 7.4 command line (via `racket -e "(list 'unquote 4)")
- Racket 7.4 (ChezScheme version) command line

**Comment by blevenson** [comment] 2019-10-04 16:49
Sorry for not giving more context.  I am running DrRacket 7.4 with language R5RS on MacOS 10.14.6.  I have attached screenshots of the two places I get the error.  When I run it on the command line, (via `racket -e "(list 'unquote 4)"), that works fine.

Is there any command I can run to get debug output from DrRacket?

Screenshots:
<img width="1440" alt="Screenshot definitions area" src="https://user-images.githubusercontent.com/6323967/66224805-cecbd280-e6a4-11e9-8e12-658b39f6fbba.png">
<img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/6323967/66224806-cecbd280-e6a4-11e9-8aaf-6c60c269d9a8.png">

**Comment by jackfirth** [comment] 2019-10-04 16:56
Huh, this is interesting. So if I set the language in DrRacket to R5RS using the language menu, then I see the same problem you do. But if I use `#lang` to specify the language instead, everything works normally. Both of the programs evaluate quickly and produce the expected result:

```racket
#lang racket
(list 'unquote 4)
```

```racket
#lang r5rs
(list 'unquote 4)
```

I don't know enough about DrRacket to have any idea what could be causing this. @blevenson as a workaround, does specifying `#lang r5rs` in each file instead of using DrRacket's language menu work for you?

**Comment by blevenson** [comment] 2019-10-04 17:09
Thanks @jackfirth , that workaround fixes the issue.

**Comment by jackfirth** [comment] 2019-10-04 21:40
Happy to help! Meanwhile, this probably ought to go in the racket/drracket repository instead of here. @spdegabrielle, could you transfer the issue? (I'm assuming you have issue transferring powers)

**Comment by spdegabrielle** [comment] 2019-10-04 22:00
@jackfirth I don’t have transfer powers.

**Comment by jackfirth** [comment] 2019-10-04 22:07
Oops. Who does?

**Comment by jbclements** [comment] 2019-10-04 22:10
Looks like I do... but really, my experience is that this could easily wind up being a problem with racket. Maybe it would be simpler just to leave it here until Robby or Matthew weighs in.

**Comment by jbclements** [comment] 2019-10-04 22:11
... or at the intersection, I should have said...

**Comment by jbclements** [comment] 2019-10-04 22:11
wait, I can plus-one myself?

**Comment by gus-massa** [comment] 2019-10-05 21:28
Note that in this program, the error is in the last line:

    ;implicit r5rs language, inside DrRacket
    (define x (list 'unquote 4))
    (display (length x))   ; ==> 2 
    (display x)            ; ==> , <just a coma and then and error>
 
I'm not 100% sure, but this doesn't look like a problem in DrRacket, but a problem in the output handler/filter that is installed by r5rs so the things look like expected. For example, the `list` in r5rs is a mutable list, but when printed it uses parenthesis instead of curly braces.

My guess is that the error is in the printing routine. Perhaps @rfinder can help to translate this example to a plain racket example because he knows better the details about the custom outputs in DrRacket, but I guess the bug is in r5rs or racket.

**Comment by rfindler** [comment] 2019-10-05 22:02
Here are two programs resembling what drracket does with the above code that give different errors.

```
#lang racket
(require compatibility/mlist)
(parameterize ((print-mpair-curly-braces #f)
               (print-vector-length #f)
               (print-graph #t))
  (pretty-write (mlist 'unquote 4)))
```
produces 
```
cadr: contract violation
  expected: (cons/c any/c pair?)
  given: (mcons 'unquote (mcons 4 '()))
  context...:
```
and this one

```
#lang racket
(define ns (make-base-namespace))
(parameterize ([current-namespace ns]
               (print-mpair-curly-braces #f)
               (print-vector-length #f)
               (print-graph #t))
  (namespace-require 'racket/pretty)
  (namespace-require 'compatibility/mlist)
  (eval '(define x (mlist 'unquote 4)))
  (eval '(display (length x)))
  (eval '(pretty-write x)))
```

produces

```
length: contract violation
  expected: list?
  given: (mcons 'unquote (mcons 4 '()))
```

**Comment by rfindler** [comment] 2019-10-05 22:03
And yes (in case it wasn't clear), if an exception gets raised by the code that drracket uses to print (at least certain parts of it), DrRacket itself can get wedged. So probably that's the only bug. Or only bugs. :)

**Comment by gus-massa** [comment] 2019-10-06 01:39
Analyzing the first expansion, the bug is in the `cadr`s in https://github.com/racket/racket/blob/044c15ec8fb2ef821fa2424de934f3343ab1b4eb/racket/collects/racket/pretty.rkt#L782-L785
It must be replaced with `(car (cadr ...))` because  in that part of the code `car` and `cdr` are arguments of the functions, are may be `mcar` and `mcdr` instead of the real `car` and `cdr`. I'll try to look if there are similar problems in other lines and add more tests.

Now I think it is strange that DrRacket gets an out of memory error. Perhaps the original error tries to print a friendly error message that includes the value of the polemic `mlist`, and printing it causes an error that  tries to print a friendly error message that includes the value of the polemic `mlist`, and printing it  causes an error that  tries to print a friendly error message that includes the value of the polemic `mlist`,  and printing it causes an error that ...

**Comment by rfindler** [comment] 2019-10-06 01:54
Sounds right about the friendly attempt. :)

**Comment by samth** [comment] 2019-10-06 02:14
I created a PR that fixes the `cadr` issue. But I haven't figured out where the call to `length` is yet (it's not in `racket/pretty.rkt`).

**Comment by gus-massa** [comment] 2019-10-06 03:32
The `length` is from my example, the second to last line in the second example should be

    (eval '(display (mlength x)))  ;  <-add an m here

**Comment by rfindler** [comment] 2019-10-06 11:19
Oops! Sorry about that.

**Closed** 2019-10-06 17:02 UTC
