### ISSUE TITLE
A bug of ~bind in syntax/parse

### ISSUE THREAD

**Issue by Syntacticlosure** [racket/racket#1729] opened 2017-06-21 11:46 UTC
Consider the code below :
```
#lang racket
(require syntax/parse)
(syntax-parse #'(x y z)
  [((~or (~and (~literal x)
              (~bind [test #'1]))
        (~and e (~bind [test #'2]))) ...)
   #'(test ...)])
```
In a  certain ~or statement, there is only one value (1 or 2) binded. I expected it to return #'(1 2 2), but the code returns an error.

**Comment by rmculpepper** [comment] 2017-06-21 19:35
The problem is that the EH version of `~or` (that is, `~or` used immediately before ellipses) doesn't allow the same attribute to occur in multiple alternatives. The normal version of `~or` behaves as you expected:

    (syntax-parse #'(x y z)
      [((~and  ;; force S version of ~or
         (~or (~and (~literal x)
                    (~bind [test #'1]))
              (~and e (~bind [test #'2])))) ...)
       #'(test ...)])
    ;; => #<syntax:11:7 (1 2 2)>

The context-sensitive meaning of `~or` is one of the biggest mistakes in the design of `syntax-parse`.

**Comment by sorawee** [comment] 2020-04-22 19:55
Can we close this? It's now clear in the documentation that `~or` is discouraged, and using `~or*` here gives the expected result.

**Closed** 2020-04-22 20:09 UTC
