### ISSUE TITLE
recovery trashed my file

### ISSUE THREAD

**Issue by hblazeviczx6r** [racket/racket#3445] opened 2020-10-18 15:09 UTC
Hi,
 I'm working on HTDP2 chapter 9 and just had a blackout. After rebooting I was pleased to see that Dr Racket is offering to recover the lost changes. However when I clicked on restore, instead of getting restored file I ended up with completely empty file. You can imagine that some f... words followed that :-).

BTW I'm working on linux version of DrRacket v7.8  on Manjaro 20.1 linux.
regards,
Hrvoje Blazevic

**Comment by pmatos** [comment] 2020-10-19 18:26
It feels like the last time DrRacket saved the file was when it was empty (saves files every 5 mins). I assume you hadn't written much into the file.

In any case, I doubt you might be able to recover whatever you had at this point. 
You can read more about backup and recovery here:
https://docs.racket-lang.org/drracket/drracket-files.html#%28part._drracket-autosave-files%29

**Comment by rfindler** [comment] 2020-10-20 00:20
Thank you for the report and I'm very sorry you lost your work!

Just for completeness I tried some things and didn't find a bug. Here's what I tried:

1. open drracket, create a file containing this content:
```
#lang racket
"a nice program"
```
2. saved the file
3. added the line `"unsaved changes"`
4. waited a few seconds for autosave to kick in
5. went to the terminal, found the pid of drracket and killed it
6. started up drracket again

At this point I got the dialog box showing that unsaved changes were detected and I clicked on "show details" and it showed me the right things. I then clicked the restore button and it was restored correctly.

So I'm not sure what we can do at this point. But if there a similar series of steps that has the wrong behavior, I'm very interested (or if that series of steps comes out different for you somehow).

**Comment by hblazeviczx6r** [comment] 2020-10-20 05:42
Hi, no need to be sorry for the lost work :-), it was just solved
exercises form most of chapter 9. I was only pissed of because the
next exercise (end of 9.5) requested to build on on the previous
exercises that I lost, so I had to do them over again.
But never mind that. The problem is real, as I can see it. First to
clear the previous comment by Paulo; I was working for more than two
hours before the blackout, so If unsaved changes were empty, that *is*
a DRScheme problem.
Now reading your procedure above, the only thing I did not do, was to
click on "show details", I went right to restore.

Maybe, just maybe, DrRacket has a problem on Manjaro??? There are some
other suspicious behaviors, that I did not think important enough to
report. For instance whenever I make a clean ordinary file (not using
Racket, but from the desktop), and name it something.rktl(rkt) and
open it in DrScheme, the language choice is lost, so I have to do it
again. As far as I remember many years ago when I was working through
HTDP1 this was not the case.
Also when I click on Teaching Languages - Beginning Student, sometimes
the OK button is shaded. Anyway If I repeat it few times, eventually I
manage to set the language.

Hrvoje

**Comment by pmatos** [comment] 2020-10-20 07:20
To be clear, I didn't mean to dismiss your problem @hblazeviczx6r . I might have worded it poorly and was too quick to close the issue. If we think there is a problem in DrRacket (although I couldn't reproduce it), let me reopen this and re-assign it.

**Comment by rfindler** [comment] 2020-10-20 15:05
@hblazeviczx6r I think the other points you mention (inability to click and forgetting previous language settings) are unrelated to the problem at hand. I have been able to get that inability to click in the language dialog sometimes myself, but not reliably. Also, the show-details button probably isn't relevant; I see the proper behavior either way.

Are you able to follow the steps that I outlined above? Do you see different behavior?

**Comment by hblazeviczx6r** [comment] 2020-10-20 15:52
Will try that tomorrow and will revert.

**Comment by hblazeviczx6r** [comment] 2020-10-21 07:17
Well, don't know what to say.
Have tested today, by waiting to see that DrScheme have written the
rescue file in the file manager, and then I actually pulled the plug.
After rebooting, the file was restored perfectly.
However, yesterday Manjaro installed several updates, among which was
a newer kernel???
Could this be the reason?

**Comment by rfindler** [comment] 2020-10-21 14:02
Oh wow-- I'm really sorry! Please don't pull the plug on your computer on my account! You can lose a lot more than just a single homework assignment if you do that!

As for the software update, I doubt it. There may still be a bug in DrRacket somewhere but we just aren't doing quite the right steps to make it happen. Sometimes understanding how to elicit bad behavior is the hard part in bugs. 

Probably best if we just close this for now and if it happens again see if you can spot some reason something seemed different and then reopen this with that new information. Ok?

**Comment by hblazeviczx6r** [comment] 2020-10-21 15:29
Ok. If it ever happens again, I'll let you know.

**Comment by rfindler** [comment] 2020-10-21 17:50
Thank you.

**Closed by rfindler** 2020-10-21 17:50 UTC
