### ISSUE TITLE
This simplest thing, does not work.

### ISSUE THREAD

**Issue by danbaron0** [racket/racket#3971] opened 2021-08-22 06:14 UTC
#lang racket

(define a (list 1 2))
(define b (list 3 4))

(define (combine c d)(set! c (append c d)))

(combine a b)

(println a)

----------------------------------

'(1 2)

**Comment by sorawee** [comment] 2021-08-22 06:37
Do you expect it to print `'(1 2 3 4)`?

If so, the behavior that you expect is known as call-by-reference. Racket (and many other programming languages, such as JavaScript and Python) does not have this behavior, so the fact that it prints `'(1 2)` is expected and correct.

```
// JS
let a = [1, 2];
let b = [3, 4];

function combine(c, d) {
  c = c.concat(d);
}

combine(a, b);
console.log(a); // [1, 2]
```

```
# Python
a = [1, 2]
b = [3, 4]

def combine(c, d):
    c = c + d

combine(a, b)
print(a) # [1, 2]
```

I will close the issue as this is not a bug. If you have any further question, feel free to ask it in the [Racket mailing list, Slack, or other channels](https://github.com/racket/racket/wiki/Racket-on-the-web).

**Closed by sorawee** 2021-08-22 06:37 UTC
