### ISSUE TITLE
racket 8.12 segfaults immediately on Fedora

### ISSUE THREAD

**Issue by juhp** [racket/racket#4981] opened 2024-04-24 04:00 UTC
Good news is Racket now builds on Fedora without any obvious problems -
the bad news is it segfaults immediately at startup

**What version of Racket are you using?**
8.12

**What program did you run?**
racket

**What should have happened?**
UI should start

**If you got an error message, please include it here.**
```shellsession
$ racket
malformed fasl-object header in petite
malformed boot file petite
Aborted (core dumped)
```

**Please include any other relevant details**
Happens for both Fedora Linux 39 and 40

What other information can I provide?

**Comment by mflatt** [comment] 2024-04-24 12:57
Thanks for the report.

Does something in the build process change the `racket` executable after it's installed? Maybe an extra operation like `strip`?

The symptom suggests that the boot file meant to be in the executable isn't being found, maybe because the relevant ELF section was removed. At the same time, it seems that `racket` ran well enough at one point with its embedded boot files to get itself installed (but I might be guessing wrong about the install process).

**Comment by juhp** [comment] 2024-04-25 15:44
> Does something in the build process change the `racket` executable after it's installed? Maybe an extra operation like `strip`?

Of course we strip and I suspect more these days. :-)
(I can try disabling stripping though I would be somewhat surprised if it helps.
Now I just tried your upstream Linux installer and it also has stripped binaries.)
I will try to look more at the Fedora build to find clues about how it might be affecting the runtime artifacts.
I may be helpful if I attach exerts of the buildlog to show what is going on, anyway:
but here it is in full anyway: 

- [Fedora Rawhide task](https://koji.fedoraproject.org/koji/taskinfo?taskID=116778183): [build.log](https://kojipkgs.fedoraproject.org//work/tasks/8183/116778183/build.log) and [root.log](https://kojipkgs.fedoraproject.org//work/tasks/8183/116778183/root.log)
- [Fedora 40 task](https://koji.fedoraproject.org/koji/taskinfo?taskID=116800727): [build.log](https://kojipkgs.fedoraproject.org//work/tasks/727/116800727/build.log) and [root.log](https://kojipkgs.fedoraproject.org//work/tasks/727/116800727/root.log)

I also did a Rawhide (devel version) [aarch64 build](https://koji.fedoraproject.org/koji/taskinfo?taskID=116781101)

(Note these scratch build logs will disappear after 2 weeks)

**Comment by mflatt** [comment] 2024-04-25 15:59
A more useful question from me would have been: is a `.rackboot` section present in the executable that crashes? My memory is hazy on this point, but I think some `strip` modes end up removing that section, which would explain the startup problem. (I should make Racket detect when a section that it expects is missing and report a more useful error in that case. On my list.)

**Comment by LiberalArtist** [comment] 2024-04-26 01:19
> A more useful question from me would have been: is a `.rackboot` section present in the executable that crashes? My memory is hazy on this point, but I think some `strip` modes end up removing that section, which would explain the startup problem.

I remembered you had found a solution in https://github.com/racket/racket/issues/3726#issuecomment-798734769:

> The problem is that a step in `rpmbuild` strips the ".rackboot" ELF section from the `racket` executable. After some digging and searching (it seems that Rust has the same kind of issue) it appears that adding
> 
> ```
> %global _find_debuginfo_opts --keep-section .rackboot
> ```
> 
> to "racket.spec.txt" solves the problem.

**Comment by juhp** [comment] 2024-04-26 02:29
I also tried a Fedora 38 [build](116866533) but again got the same runtime segfault result.

**Comment by juhp** [comment] 2024-04-26 02:42
This is the most relevant parts of the current spec I am using:

```rpm-spec
%prep
%autosetup -p1

# Remove bundled libffi
rm -r src/bc/foreign/libffi

%build
cd src

%configure \
        --enable-pthread \
        --enable-shared \
        --enable-libffi \
        --disable-libs \
        --enable-lt="%{_bindir}/libtool" \
        --disable-strip

%make_build

%install
%make_install -C src

# Delete mred binaries and replace them with links.
rm %{buildroot}%{_bindir}/mred
rm %{buildroot}%{_bindir}/mred-text
ln -s gracket %{buildroot}%{_bindir}/mred
ln -s gracket-text %{buildroot}%{_bindir}/mred-text

# Fix the rpath error.
chrpath --delete %{buildroot}%{_bindir}/racket
chrpath --delete %{buildroot}%{_libdir}/racket/gracket

# Fix paths in the desktop files.
sed -i "s#%{buildroot}##g" %{buildroot}/%{_datadir}/applications/*.desktop

# Validate desktop files
desktop-file-validate %{buildroot}/%{_datadir}/applications/*.desktop

# Remove the executable bit on legacy template file
chmod -x %{buildroot}%{_libdir}/racket/starter-sh

# disable check-buildroot for
# (see https://github.com/racket/racket/issues/3878 discussion)
%undefine __arch_install_post

%ldconfig_scriptlets
```

**Comment by LiberalArtist** [comment] 2024-04-26 19:14
The issue is specifically that the tool which strips the debug info from ELF files to form separate `-debuginfo` subpackages needs to be instructed not to strip away the custom `.rackboot` ELF section. So you should just need to add the line, somewhere early in the specfile:
```specfile
%global _find_debuginfo_opts --keep-section .rackboot
```
There's a little more info on what happens by default [here, under "Post-build ELF object processing"](https://src.fedoraproject.org/rpms/redhat-rpm-config/blob/rawhide/f/buildflags.md#post-build-elf-object-processing) (the anchor within the page isn't working for me).

There are other things that maybe should be tweaked, but probably better to get a working package before worrying about them.

**Comment by juhp** [comment] 2024-04-28 04:34
Thanks @LiberalArtist - that worked great!

I wonder if there are any build-time tests I should run or at least way to verify the executable works.
Well maybe even just running `racket --help` or `racket --version` would be enough, I can try,
though I dunno if racket can run from a staging directory, perhaps some envvar needed?

I would also be very grateful for any other suggestions on how to improve the fedora .spec file.
Let me post a link anyway once I have pushed it.

**Comment by shhyou** [comment] 2024-07-29 01:40
Closed as resolved by https://github.com/racket/racket/issues/4981#issuecomment-2079982664

@juhp You can install the `racket-test` package and run `raco test -l tests/racket/test`. See examples at https://github.com/racket/racket/blob/240aa086c548440e0b11641c40cf79e393a560a4/.github/workflows/ci-push-x86_linux.yml#L239-L244.

**Closed by shhyou** 2024-07-29 01:40 UTC
Labels: build

**Comment by juhp** [comment] 2024-08-20 10:27
I can't use the network in the Fedora Buildsystem, but potentially some such CI test could be added.
