### ISSUE TITLE
Release Regressions for 8.13

### ISSUE THREAD

**Issue by jbclements** [racket/racket#4980] opened 2024-04-23 16:19 UTC
Current Release vs Next Release
========================================
>>> fetching https://pkg-build.racket-lang.org/summary.rktd
>>> fetching https://plt.cs.northwestern.edu/release-pkg-build/summary.rktd
### Build Failures
- [ ] YACP https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/YACP.txt
- [ ] clang https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/clang.txt
- [ ] digimon https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/digimon.txt
- [ ] odysseus https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/odysseus.txt
### Test Failures
- [ ] struct-defaults https://plt.cs.northwestern.edu/release-pkg-build/server/built/test-fail/struct-defaults.txt
### Other Failures
- [ ] video-v0-0

**Comment by sorawee** [comment] 2024-04-23 16:20
This is a duplicate of #4978, FWIW.

**Comment by jbclements** [comment] 2024-04-23 16:40
Awesome, many thanks! Will close.

**Closed** 2024-04-23 16:40 UTC
