### ISSUE TITLE
Warn when using `raco pkg install --link` for directories that don't have an info.rkt file

### ISSUE THREAD

**Issue by samth** [racket/racket#1095] opened 2015-10-19 13:50 UTC
@andmkent did this accidentally (pointing to the parent dir), and a warning would be helpful.

**Comment by sorawee** [comment] 2023-07-22 01:30
#4626 is a duplicate of this issue, but since there is a discussion there, let's close this one instead.

**Closed by sorawee** 2023-07-22 01:30 UTC
