### ISSUE TITLE
Error invoking tool #<path:C:\Program Files\Racket\share\pkgs\drracket\drracket>;"syncheck.rkt" when starting DrRacket

### ISSUE THREAD

**Issue by Reilithion** [racket/racket#4658] opened 2023-05-26 00:55 UTC
**What version of Racket are you using?**
8.9

**What program did you run?**
DrRacket

**What should have happened?**
DrRacket should open without error.

**If you got an error message, please include it here.**
Error invoking tool #<path:C:\Program Files\Racket\share\pkgs\drracket\drracket>;"syncheck.rkt"

instantiate-linklet: mismatch;
 reference to a variable that is not exported
  name: syncheck:add-unused-require19.1
  exporting instance: "C:\Program Files\Racket\share\pkgs\drracket-tool-lib\drracket\private\syncheck\syncheck-local-member-names.rkt"
  importing instance: "C:\Program Files\Racket\share\pkgs\drracket\drracket\private\syncheck\gui.rkt"
  possible reason: modules need to be recompiled because dependencies changed
  possible solution: running `racket -y`, `raco make`, or `raco setup`
  context...:
   body of "C:\Program Files\Racket\share\pkgs\drracket\drracket\private\syncheck\gui.rkt"
   C:\Program Files\Racket\share\pkgs\drracket\drracket\private\tools.rkt:294:2
   C:\Program Files\Racket\share\pkgs\drracket\drracket\private\tools.rkt:72:0: load/invoke-all-tools
   .../unit/lang.rkt:84:9
   C:\Program Files\Racket\share\pkgs\drracket\drracket\private\link.rkt:57:0
   body of "C:\Program Files\Racket\share\pkgs\drracket\drracket\tool-lib.rkt"
   body of "C:\Program Files\Racket\share\pkgs\drracket\drracket\private\drracket-normal.rkt"
   body of "C:\Program Files\Racket\share\pkgs\drracket\drracket\drracket.rkt"

**Please include any other relevant details**
This is a fresh install on Windows 10. I actually was getting this error for a while with versions 8.7 (I believe) and 8.8 (for certain). I decided to try completely uninstalling and then reinstalling Racket, including deleting any remaining directory from Program Files (there was one in Program Files (x86) but this may have been from quite some time ago).

After reinstall the error continued to come up when starting DrRacket. I tried closing out, renaming my 'AppData\Roaming\Racket' folder to something else, and starting DrRacket again. The error continues to appear. I've tried both `racket -y` and `raco setup`, neither of which get the error to stop coming up. `raco make` expects a target, and I have no idea what to tell it, so this option does not appear to be helpful in this case.

It doesn't _seem_ like it's causing any major issues with DrRacket running and doing its job. I can still edit .rkt files and run them from DrRacket. Syntax highlighting still works. But it's an irritation, and it leaves a console window open with the error message for as long as DrRacket is running. I also wonder if some piece of functionality that I don't often use might be compromised.

**Comment by mflatt** [comment] 2023-05-26 03:09
I wonder if timestamps are somehow getting confused during install. Does anything change if you set the `PLT_COMPILED_FILE_CHECK` environment variable to `exists` before starting DrRacket? Or if you run `raco setup` (which probably needs administrator permissions, and maybe run as `"C:Program Files\Racket\raco" setup`).

**Comment by rfindler** [comment] 2023-05-26 14:21
> [ ... ] I also wonder if some piece of functionality that I don't often use might be compromised.

Yes, you're missing some functionality that I consider very important, namely automatic identification of syntax errors (without having to click the Run button) and navigation based on the binding structure of the program (like when you mouse over an identifier, others that are bound by the same binder light up and you have c:x;n and related keybindings that let you jump from one use of an identifier to the next).

**Comment by Reilithion** [comment] 2023-05-27 02:20
> I wonder if timestamps are somehow getting confused during install. Does anything change if you set the `PLT_COMPILED_FILE_CHECK` environment variable to `exists` before starting DrRacket? Or if you run `raco setup` (which probably needs administrator permissions, and maybe run as `"C:Program Files\Racket\raco" setup`).

Running raco setup this way (as administrator and from working directory "C:\Program Files\Racket\") resolved the error. Not sure what I was doing wrong before, but the error stops coming up after this step.

I tried uninstalling and reinstalling again and interestingly the error returns. I think it'd be weird I'm the only one complaining of this error when running on Windows if it's an actual problem in the distribution but... could it be a problem in the distribution? What else could cause this? Does Racket use the Windows registry in any big way, or are there cached files anywhere that remain after uninstall and could cause this?

**Comment by mflatt** [comment] 2023-05-27 02:37
Normally, the installer should unpack files with their original timestamps. Is it possible that something in your filesystem or OS setup modifies recently written files or otherwise adjusts timestamps on unpacked files? For example, I can imagine anti-malware tools doing something like that (although I don't know whether any anti-malware tools actually work that way), and I can imagine a non-NTFS filesystem not treating timestamp requests the same way.

**Comment by sorawee** [comment] 2023-07-27 07:42
I will close this issue, since the original problem is fixed. It would be great, though, if @Reilithion can confirm if the problem is due to filesystem.

**Closed by sorawee** 2023-07-27 07:42 UTC
