### ISSUE TITLE
Release regressions for 8.4

### ISSUE THREAD

**Issue by samth** [racket/racket#4125] opened 2022-01-12 15:18 UTC
Here are the current results for checking release regressions.

### Known problems that aren't about the release
- [ ] satore https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/satore.txt (capitalization of files)
- [ ] video-v0-0 intentional conflict between packages

### Typed Racket issues 

All of these have open PRs that fix them but haven't been merged
- [x] cs7480-util https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/cs7480-util.txt (requires TR internals that changed)
- [x] delay-pure https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/delay-pure.txt (new TR kind system)
- [ ] graphics https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/graphics.txt (new TR kind system)
- [ ] w3s https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/w3s.txt (new TR kind system)

### Build Failures
- [x] k-infix https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/k-infix.txt
- [x] nix https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/nix.txt (package removed)
- [x] splitflap https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/splitflap.txt
- [x] splitflap-doc https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/splitflap-doc.txt
### Test Failures
- [ ] racket-language-server https://plt.cs.northwestern.edu/release-pkg-build/server/built/test-fail/racket-language-server.txt (failed last release too)
- [x] rascas https://plt.cs.northwestern.edu/release-pkg-build/server/built/test-fail/rascas.txt

**Comment by samth** [comment] 2022-01-12 15:27
Both splitflap and k-infix depend on memoize, so I wonder if that's related.

**Comment by otherjoel** [comment] 2022-01-12 15:28
For splitflap the problem appears to be with [this line](https://github.com/otherjoel/splitflap/blob/main/splitflap-lib/private/validation.rkt#L480). I’m at work but I’ll look into it as soon as I can.

**Comment by samth** [comment] 2022-01-12 15:32
I think just dropping the call to `bytes->string/utf-8` seems sufficient.

**Comment by mflatt** [comment] 2022-01-12 15:38
The problem with `splitflap` is probably because `system-language+country` was broken in CS and produced bytes when it should have produced a string, and the release candidates makes CS like BC.

The problem with `k-infix` is a Scribble change that avoids multiple expansions in `#%module-begin`, and I'm looking at a way to support the old behavior.

**Comment by otherjoel** [comment] 2022-01-12 15:42
> `system-language+country` was broken in CS and produced bytes

Right, I'll add a test there so splitflap doesn’t break for older versions.

**Comment by samth** [comment] 2022-01-13 20:52
cc @jeapostrophe for racket-language-server and @Metaxal for rascas.

**Comment by jeapostrophe** [comment] 2022-01-14 21:19
`racket-language-server` isn't mine and is archived. Mine is `racket-langserver`

**Comment by jbclements** [comment] 2022-01-19 19:07
Wrote to @Metaxal about rascas failure, I can reproduce the bug on some platforms.

**Comment by jbclements** [comment] 2022-01-19 19:09
k-infix failure: not a release blocker

**Comment by Metaxal** [comment] 2022-01-19 20:39
Sorry I missed the first bunch of emails. Yes, at quick glance it appears to be due to non-determinism, due to hashes in `contract-let*`. I don't think that's anything to worry about, except that I'm not sure how to fix the test case :grimacing:

**Comment by jbclements** [comment] 2022-01-19 21:07
How many different shapes are possible? Could the test case just be a big 'or' of all the possibilities?

**Comment by jbclements** [comment] 2022-01-19 21:08
Regardless, I'm going to list this as "not a blocker" for the release. It's probably in your interest to fix it, though, so that if it breaks in the next release it will be listed as a regression and not just go into the big "broken" pile.

**Comment by Metaxal** [comment] 2022-01-19 21:11
I will definitely fix it soon (by contrast to `satore`, which requires me to setup many things before I can apply even a small fix.)

**Comment by m4burns** [comment] 2022-01-21 01:13
Package `rfc6455` installs but fails to `require` on today's snapshot (8.4.0.3):

```
Welcome to Racket v8.4.0.3 [cs].
> (require net/rfc6455)
procedure-reduce-arity-mask: arity mask of procedure does not include requested arity mask
  procedure: #<procedure:.../rfc6455/server.rkt:49:4>
  requested arity mask: -4
 [,bt for context]
 ```

**Comment by m4burns** [comment] 2022-01-21 01:20
Re: `rfc6455`: the issue is

```
> (procedure-rename (make-keyword-procedure (lambda (ks vs x . r) void)) 'foo)
procedure-reduce-arity-mask: arity mask of procedure does not include requested arity mask
```

**Comment by mflatt** [comment] 2022-01-21 03:08
@m4burns Thanks for the `procedure-rename` report! The problem won't affect v8.4, since it's related to changes after the release branch. The underlying problem with `procedure-arity` affects v8.4 and earlier, but that turns out not to be a new problem (and we would normally not try to fix old problems like that at this point).

**Comment by bennn** [comment] 2022-01-24 20:42
The `cs7480-util` PR is merged now, but I've also taken that package down. It depended on TR internals and we weren't using it.

**Comment by plane** [comment] 2022-01-26 10:16
Is this relevant here? https://github.com/racket/racket/issues/4141  I believe this problem is new in 8.4.

**Comment by Metaxal** [comment] 2022-01-31 21:12
`rascas` has been fixed a per  @jbclements' suggestion. Thanks!

**Comment by Metaxal** [comment] 2022-05-08 13:17
Can this issue be closed now?

**Comment by jbclements** [comment] 2022-05-08 21:50
Sure, good point.

**Closed by jbclements** 2022-05-08 21:50 UTC
