### ISSUE TITLE
#:do keyword in syntax-parse having no effect

### ISSUE THREAD

**Issue by ashton314** [racket/racket#4721] opened 2023-08-16 18:03 UTC
**What version of Racket are you using?**
8.10 [cs]

**What program did you run?**

```racket
#lang racket

(require syntax/parse/define)

(define-syntax (foo stx)
  (syntax-parse stx
    [(_ whatever)
     #:do (printf "Got ~a in macro\n" #'whatever)
     #'(λ () whatever)]))

(foo 42)
```

output:

```
#<procedure:...x_parse_do_test.rkt:10:7>
> 
```

**What should have happened?**

I would have expected to see the line "Got #<syntax:...> in macro" printed.

Perhaps this is me misunderstanding how the `#:do` keyword is supposed to behave, but the docs make it sound like this should work.

Yes, I know I can just stuff that statement in there without the `#:do` keyword and it will print, but I'm curious about the behavior of that keyword in situations like this.

I noticed a line that seemed a little suspicious… not sure if it's *actually* related, but I thought I'd put it here just in case:

```racket
(define (simplify:normalize-and p)
  (define (pattern->list p)
    (match p
      …
      [(action:do '()) null]
      …))
  …)
```

That's from `collects/syntax/parse/private/rep.rkt` line 1414.

**If you got an error message, please include it here.**

(No error)

**Please include any other relevant details**

macOS 13.5; M1 Pro hardware

**Comment by sorawee** [comment] 2023-08-16 18:16
I will close this issue, as this is not a bug. For discussion about improving error message or finding a way to reduce this misunderstanding, see #4489.

**Closed by sorawee** 2023-08-16 18:16 UTC

**Comment by ashton314** [comment] 2023-08-16 21:29
Thank you very much for clearing up the misunderstanding. If I get the chance later, maybe I can open a PR to add an example or something to the docs: https://docs.racket-lang.org/syntax/stxparse-specifying.html#%28tech._pattern._directive%29

I see now how the docs explain this behavior, but I hope you can see how I missed it. 🙃
