### ISSUE TITLE
Warning in jitinline.c in VSE2008 (32 bits)

### ISSUE THREAD

**Issue by gus-massa** [racket/racket#1167] opened 2015-12-14 18:17 UTC
Compiling in VSE2008 (32 bits) I get a few warnings (it's not a new warning, I saw it before.):  

```
..\..\racket\src\jitinline.c(4826): warning C4293: '<<' : shift count negative 
or too big, undefined behavior

..\..\racket\src\jitinline.c(4842): warning C4293: '<<' : shift count negative 
or too big, undefined behavior
```

See: [jitinline.c#L4826](https://github.com/racket/racket/blob/master/racket/src/racket/src/jitinline.c#L4826) and [jitinline.c#L4842](https://github.com/racket/racket/blob/master/racket/src/racket/src/jitinline.c#L4842)

I guess it needs a `#ifdef SIXTY_FOUR_BIT_INTEGERS` like in [jitinline.c#L4858](https://github.com/racket/racket/blob/master/racket/src/racket/src/jitinline.c#L4858) but I'm not sure about the details.

**Comment by gus-massa** [comment] 2021-02-03 22:22
This was posted a long time ago. I'm not sure it is still a problem. Meanwhile, the code had moved to another directory and a few lines down. The current positions are:

4826 -> 
https://github.com/racket/racket/blob/ea96e2d3042b1e4ff0d39ef506bb72a2f204d623/racket/src/bc/src/jitinline.c#L5685

4842 ->
https://github.com/racket/racket/blob/ea96e2d3042b1e4ff0d39ef506bb72a2f204d623/racket/src/bc/src/jitinline.c#L5701

4858 -> https://github.com/racket/racket/blob/ea96e2d3042b1e4ff0d39ef506bb72a2f204d623/racket/src/bc/src/jitinline.c#L5717-L5725

**Comment by mflatt** [comment] 2021-04-28 01:39
This is still true, but I'm going to close as a BC "won't fix".

The problem is the way old-style GNU lightning works in terms of macros. When a literal value is provided to a macro, then sometimes there are subexpressions that are obviously wrong — but those subexpressions are guarded by conditionals.

To illustrate, the following program provokes the same compiler warning:

```
extern int big_shift(int a, int b);

#define shift(a, b) ((a < 10) ? (b << a) : big_shift(a, b))

int f(int b) {  return shift(100, b); }
```

Other compilers, such as GCC and Clang and maybe newer MSVC, recognize that `b << 100` won't happen because `100 < 10` is not true. So, that's why this is not as much of a problem for BC on most build environments. Still, CS is a better solution overall.

**Closed by mflatt** 2021-04-28 01:39 UTC
