### ISSUE TITLE
Missing web contents

### ISSUE THREAD

**Issue by AGoh2019** [racket/racket#4579] opened 2023-02-15 03:25 UTC
**What version of Racket are you using?**
e.g., 8.8

**What program did you run?** 
-  Help - Related Web Sites -> Program by Design
-  Help - Tool Web Sites -> Swindle
-  Both sites do not exist

**Comment by jryans** [comment] 2023-03-15 13:21
* [Program by Design](http://programbydesign.org) appears to load currently
* [Swindle](http://www.barzilay.org/Swindle/) does not, there is an [open PR](https://github.com/racket/swindle/pull/3) which changes to related site that is live

**Comment by sorawee** [comment] 2023-07-22 01:01
Both links now work. Closing.

**Closed by sorawee** 2023-07-22 01:01 UTC
