### ISSUE TITLE
Cyclic require runs forever in DrRacket (MacOS)

### ISSUE THREAD

**Issue by sorawee** [racket/racket#2681] opened 2019-06-04 15:39 UTC
```
;; a.rkt
#lang racket
(require "a.rkt")
1
```

Under normal circumstance, running the file in DrRacket will result in an error, as expected.

However, by clicking "Run" repeatedly rapidly (or cmd+R), it seems that DrRacket becomes stuck in an infinite loop. Even after we "Stop" the running, any new attempt to run the file normally will also gets stuck as well. The only way to fix the problem is to restart DrRacket.

Observation: suppose we remove the require statement, then DrRacket will now run fine. However, by adding the require statement back, the problem will come back as well.

**Comment by sorawee** [comment] 2019-06-04 15:51
Here's  GIF demonstrating the problem

![racket-cyclic](https://user-images.githubusercontent.com/9099577/58893869-cd15e200-86a5-11e9-9d74-f572a9c9d07d.gif)

**Comment by ddevz** [comment] 2020-12-29 16:39
Looking into it, it's possible it's the same problem.  It was happening reliably every time for me, but I never tried closing drracket and open it again.  Today when I started drracket and tried to run my test case, it just gave me the cycle error message. So perhaps you are correct in that i accidentally triggered this bug during my initial trials sometime and my original assumption that it was actually trying to cyclically load modules that weren't actually cyclic seem to be wrong.  So I'll give 90% chance it's the same issue.


Of interest, replicating what you report here, it looks like hitting run, then hitting it again before the first run completes is what triggers your reported issue.

Also, to help refine your bug report:  I replicated your bug report in drracket 7.2 on linux

**Comment by ddevz** [comment] 2020-12-29 16:46
Oh, I should also mention that this also happens with my example in racket/drracket#448 *even though there is no actual cyclic require*, just a false-positive cyclic require error message!

(This might help narrow down where in drracket the issue is)

**Comment by mflatt** [comment] 2021-06-23 23:33
I think the main problem here is that DrRacket creates the user eventspace thread in a suspend-to-kill mode (which was a change from a few versions back). That broke the compilation manager's lock-release strategy of detecting when a thread that holds a lock will never use it again. So, as far as I can tell, the problem wasn't really about cyclic requires, but about hitting Cmd-R at the right time while an attempt to compile was in progress.

Before working out this relatively straightforward problem, I also found a couple of race conditions in the implementation of the lock for parallel compilation as used by DrRacket  (but not used by `raco setup`).

**Comment by mflatt** [comment] 2021-06-23 23:33
I think the main problem here is that DrRacket creates the user eventspace thread in a suspend-to-kill mode (which was a change from a few versions back). That broke the compilation manager's lock-release strategy of detecting when a thread that holds a lock will never use it again. So, as far as I can tell, the problem wasn't really about cyclic requires, but about hitting Cmd-R at the right time while an attempt to compile was in progress.

Before working out this relatively straightforward problem, I also found a couple of race conditions in the implementation of the lock for parallel compilation as used by DrRacket  (but not used by `raco setup`).

**Closed** 2021-06-23 23:34 UTC
