### ISSUE TITLE
Racket memory spirals out of control – sometimes garbage is never collected

### ISSUE THREAD

**Issue by plane** [racket/racket#3832] opened 2021-05-17 00:02 UTC
**Racket version**: Racket 8.1 CS, but I believe the same problem may occur with 8.0 CS

**Problem**: Runaway memory usage that is never GC'ed

**Summary**: Sometimes when I leave Racket open in the background, I notice my system is running poorly, so I check and find that Racket has used all 32GB of memory!  

**Example 1**: [Windows 10] Sometimes, DrRacket stops GC'ing while it's out-of-focus.  I can move my mouse in circles over the DrRacket window, and it uses more and more memory until my computer starts swapping, ignoring the memory limit.  But if I click on the DrRacket window, a GC occurs.  At this point, if I alt-tab away from DrRacket, it will begin leaking memory again.

I've made two recordings of what this looks like, which you can find here: https://www.quarplet.com/racket-gc-problem/

**Example 2**: [Debian Linux] On a separate system running Linux, I use `vim` with `racket-langserver`.  Sometimes I notice the langserver using more and more memory until I hit 32GB.  I think this is likely to be a related problem, which is why I'm filing this bug under Racket rather than DrRacket specifically.

**Example 3**: [AntiX Linux] Three days ago a user named talgu posted about a similar problem on Reddit:

> I have something of a problem. Whenever I start DrRacket it simply starts consuming increasingly large amounts of RAM until my entire system stops and I have to reboot. This happens really quickly too, less than two minutes, without any interaction with it.
> 
> Is there some way I can prevent this from happening? It has rendered DrRacket completely unusable for me. I have Racket version 8.0, from the website, and I'm running AntiX Linux off a live disk. I have 3.7G RAM and 2G swap.
>
> (https://old.reddit.com/r/Racket/comments/nbijfh/limiting_drrackets_memory/)

I imagine this is a related problem, so I'm including it here, although their description isn't quite the same as mine.  Also, they didn't say if they were on CS or BC, but since they said 8.0 without specifying I would guess they were also on CS.

**Additional details**: This problem is *not consistent*.  Right after I open DrRacket, I do not see this problem.  I can tab out, move my mouse in circles, do whatever, and Racket will stay at a low memory usage and I can see the GC icon flash on often.  I don't know yet how to reliably reproduce the problem :(  It does seem to happen after I've had Racket open for a while in the background.

**Comment by plane** [comment] 2021-05-17 12:43
I've installed 8.1 BC on both Windows and Linux, and so far I haven't run into the problem.  It seems like this problem only happens on CS.

**Comment by mflatt** [comment] 2021-05-17 14:55
Thank you for the report and videos!

This may be related to  #3459 — which, as you'll see, I've had trouble replicating.

Since the problem has been so difficult to replicate, and since we've had relatively few reports for a problem that creates such a big problem, I think we're probably missing some key ingredient. The idea that it may be related to an application being in the background is useful, so I'll try more things along those lines. Of course, anything else you figure out about how to replicate the problem would be very welcome.

**Comment by plane** [comment] 2021-05-18 19:09
talgu replied on Reddit:

> Thanks, I did use CS. I have now tested BC and it doesn't cause the same issues at all. It's very well behaved. This solves the issue for me at least.
>
> (https://old.reddit.com/r/Racket/comments/nbijfh/limiting_drrackets_memory/)

Just wanted to add that info here too.

**Comment by plane** [comment] 2021-05-19 17:55
I edited `racket-langserver` to include `(dump-memory-stats)` in its main loop, and I got dumps from both CS and BC:

  https://www.quarplet.com/racket-gc-problem/dump-cs.txt
  https://www.quarplet.com/racket-gc-problem/dump-bc.txt

It only took about 30 seconds for CS to use 5GB of memory.  On BC memory usage stayed constant around 600MB.

I noticed this part at the bottom of the CS dump:

     #<critical-winder>     36,833,349 1,178,667,168 |  36,833,349 1,178,667,168
     pair                   74,758,647 1,196,138,352 |  74,874,500 1,197,992,000
     procedure              73,953,732 2,371,971,472 |  73,959,249 2,372,156,416
     total                  187,602,777 4,926,699,832 |  187,771,984 4,933,482,136

Maybe that could be helpful info?

**Comment by samth** [comment] 2021-05-19 20:23
That indeed seems like a lot of `critical-winder`s. As far as I can tell, while running Racket they should only be created when Chez's `parameterize` or `fluid-let` is used.

**Comment by samth** [comment] 2021-05-20 15:03
Can you provide some detailed instructions for how you set everything up, so that I can try to reproduce this?

**Comment by plane** [comment] 2021-05-21 14:32
I think I accidentally left out a super important detail!

The `racket-langserver` behavior is on Debian *under WSL2*.  I took the time to write up a set of instructions, and I followed those instructions on a separate Linux Mint install (not under WSL2), and Racket 8.1 CS seemed to work perfectly.  So maybe there's an interaction with WSL2 causing the problem?  (And maybe I should have put these into separate bug issues in the first place?  My apologies for making a mess of things!)

Anyway, these are the instructions:

1. Install Racket 8.1 CS
2. `raco pkg install racket-langserver`
3. Install VIM 8.1
4. Install `plug.vim`:

    Type at a console:

        curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

5. Install `vim-lsp` and `vim-lsp-settings`:

    Place these lines in `.vimrc`:

        call plug#begin('~/.vim/plugged')
            Plug 'prabirshrestha/vim-lsp'
            Plug 'mattn/vim-lsp-settings'
        call plug#end()

        augroup filetypedetect
            au! BufRead,BufNewFile *.rkt          setfiletype racket
        augroup END

6. Open VIM and type:

        :PlugInstall

    This will install the plugins you added to `.vimrc`.

7. Close vim, then open a new `.rkt` file.

       $ vim foo.rkt

8. Now it should prompt you to install langserver support for racket.  Type:

       :LspInstallServer

9. The langserver starts working (it will tell you if you have syntax errors etc.) but memory starts spiraling out of control

**Comment by samth** [comment] 2021-05-21 14:37
Aha, that explains why I didn't see the behavior on Linux myself. Thank you for the very detailed instructions!

**Comment by mflatt** [comment] 2021-05-21 23:32
@plane - Thanks for the instructions! Unfortunately, I haven't been able to provoke bad behavior by trying those steps, so far.

My Windows/WSL2 setup doesn't include an X server, and I used xfvb-run. Do you have an X server set up for use with WSL?

**Comment by plane** [comment] 2021-05-22 00:53
Yes, I am using this X server:

https://sourceforge.net/projects/vcxsrv/

Which I am invoking outside WSL2 with this command:

    "C:\Program Files\VcXsrv\vcxsrv.exe" :0 -ac -terminate -lesspointer -multiwindow -clipboard -wgl -dpi auto

**Comment by mflatt** [comment] 2021-05-24 15:14
@plane helped track down the racket-langserver-on-WSL problem to a bug handling glib logging when called from an OS-level thread that wasn't created by Racket. That's now fixed in the latest snapshot builds at https://www.cs.utah.edu/plt/snapshots/

It's possible that memory problems with DrRacket running in the background on Windows were due to the same bug, but I think probably not. The glib-logging bug isn't something where a GC would reset memory use (even to have it start growing again). But any reports on whether the new snapshot behaves the same or different on Windows would be appreciated.

**Comment by plane** [comment] 2021-05-28 21:54
Unfortunately, I have run into the memory problem with DrRacket a couple times since the fix.  It seems to be the same behavior as before (when DrRacket is in that state, I can move my mouse around to increase memory, and clicking to focus DrRacket causes a GC).  So I guess that was a separate problem.

This is on version 8.1.0.6--2021-05-24(18a95c3/a) [cs] on Windows 10.

**Comment by mflatt** [comment] 2021-06-01 21:15
I've finally found a way to replicate the problem: do something in DrRacket that opens a web page. More generally, use `shell-execute` to open a URL.

It looks like the problem is that `shell-execute` allows Windows events to be dispatched, but `shell-excute` binds to the underlying C function in a way that doesn't cooperate the the Racket CS FFI expectation on callbacks. As a result, when a Windows event is dispatched and handled by a callback, interrupts are left in a disabled state (and GCs are normally triggered by an interrupt).

I don't yet know why clicking on DrRacket to bring it to the foreground allows a garbage collection to happen, but I'll investigate further, just in case that turns out to be a second problem that interacts with the `shell-execute` problem.

**Comment by mflatt** [comment] 2021-06-01 21:26
It looks like moving DrRacket to the foreground is relevant because it triggers a bitmap allocation for some refresh, which involves `make-phantom-bytes`, which includes an explicit check on memory use and can force an immediate garbage collection (without relying on an interrupt).

**Comment by mflatt** [comment] 2021-06-01 21:53
I've pushed a repair for the `shell-execute` problem (and investigating the effect of clicking to bring to the foreground did not uncover another problem). Snapshot builds 20210602 and later will have the repair.

**Comment by plane** [comment] 2021-06-05 01:05
So far everything seems good!  I haven't run into the memory issue with DrRacket using 8.1.0.6--2021-06-02(f31c717/a) [cs] over the past few days.  Thank you for the fixes!

**Comment by sorawee** [comment] 2021-06-10 14:12
Fixed.

**Closed by sorawee** 2021-06-10 14:12 UTC
Labels: bug
