### ISSUE TITLE
installing local packages on minimal Racket sometimes produces odd errors

### ISSUE THREAD

**Issue by samth** [racket/racket#2928] opened 2019-11-25 16:56 UTC
Here are two places where it happened:

https://github.com/racket/typed-racket/runs/319607469#step:4:1349

https://github.com/Bogdanp/web-server/runs/316775917#step:4:1214

Both places the error is of the form:

```
raco setup: error: during making for <pkgs>/htdp-lib/lang (HtDP Languages)
raco setup:   instantiate: unknown module
raco setup:     module name: #<resolved-module-path:"/usr/share/racket-7.5.0.7/collects/xml/plist.rkt">
raco setup:     compiling: <pkgs>/htdp-lib/lang/htdp-langs.rkt
```

However, it's not clear why that file should be hard to find, since it's part of the "base" package. The other seemingly-missing files are also in packages are installed.

**Comment by mflatt** [comment] 2019-11-25 17:17
The problem is related to recompilation of VM-independent ".zo" files to VM-/platform-specific ".zo" files. In past investigations, I have not been able to figure out whether it's a bug in the compilation manager (which seems likely) or a bad failure mode when files have gotten mangled (which has been the case sometimes).

This is good evidence that there's still something wrong in the compilation manager, perhaps a race condition related to filesystem state.

**Comment by samth** [comment] 2019-11-25 17:18
I attempted to reproduce things locally but ran into #2927.

**Comment by mflatt** [comment] 2019-11-25 17:35
On further inspection, this appears to be a problem with incompatible ".zo" files, but one that the compilation manager should be able to handle more gracefully (and probably it just doesn't).

In more detail: Built packages for a snapshot work work only for the snapshot builds. The ".zo" -> ".zo" shortcut shouldn't be used in that case, but probably something is going wrong with the decision on whether to try a ".zo" -> ".zo" conversion. That's consistent with other cases that I've seen, where incompatible ".zo" files were the problem; I didn't previously investigate whether incompatible ".zo" files should be handled better, because that combination shouldn't happen with distribution builds and I was trying to get distribution builds to work.

**Comment by samth** [comment] 2019-11-25 17:40
Does this mean that there's something different I should do, or is this "just" a compilation manager bug?

**Comment by mflatt** [comment] 2019-11-25 17:55
What's the motivation for using snapshot packages?

They're never going to work as built unless you change the checkout build to start with machine-independent mode, and them they'll only work sometimes. If the fact that package are built is not important, then installing with `--source` would side-step the problem.

**Comment by samth** [comment] 2019-11-25 18:08
The motivation for that particular configuration is to build the package under test without needing to install/rebuild packages that might depend on it. For example, install Typed Racket without rebuilding the math library, which is what would happen when taking a full snapshot build and updating the Typed Racket packages.

**Comment by mflatt** [comment] 2019-11-25 18:31
That doesn't sounds like something that can work. I can see taking such fragile shortcuts during development, but when would it make sense for testing?

**Comment by samth** [comment] 2019-11-25 21:33
I think I was unclear earlier.

I'd like to install minimal Racket, install Typed Racket (from git), and then test it. If I install a "full" snapshot, then installing a new version of TR also requires re-building large portions of the distribution, such as DrRacket. 

It sounds like the following is the case:

1. If I use `--source` then everything ought to work, at the cost of installing Typed Racket being much slower.
2. If I don't use `--source`, then things currently go wrong because `typed-racket-doc` depends on some packages that depend on `typed-racket-lib` and thus the conversion (which maybe has bugs) encounters a situation it doesn't like.
3. The built packages in the catalog that minimal Racket snapshots point to contain portable `.zo` files and therefore any installation of them will require conversion.

Is that correct?

Given these problems, and the fact that the built packages are in vm-independent form, it's probably not helpful anyway to use minimal snapshots, so I won't try to do that, but it does seem like this ought to work (even if not be faster).

**Comment by mflatt** [comment] 2019-11-25 21:53
If you let things that depend on TR get rebuilt, it would still be useful for use snapshots to avoid rebuilding things that *don't* depend on TR. Fixing/improving the compilation manager would give you that.

**Comment by samth** [comment] 2019-11-25 21:55
Well, I already get that by just using the full snapshot and upgrading TR (if I understand you correctly).

**Comment by mflatt** [comment] 2019-11-25 21:59
Yes, that makes sense.

**Comment by mflatt** [comment] 2019-12-20 16:56
This problem should be fixed: no more odd errors. It's not necessarily any faster than updating after installing, though.

The odd errors reflected a bug in the compilation manager that would sometimes interfere with snapshot builds. So, I was very happy to have this example that exposed the bug more clearly and consistently.

**Closed** 2019-12-20 16:58 UTC
