### ISSUE TITLE
Failure on multi-layer contracted struct with parent

### ISSUE THREAD

**Issue by camoy** [racket/racket#3266] opened 2020-06-27 04:43 UTC
Problem occurs when attaching contracts to a struct with a parent that goes through multiple `contract-out` layers.
```rkt
#lang racket

(module first racket
  (provide (contract-out (struct foo ([x any/c])))
           (contract-out (struct (bar foo) ([x any/c]))))
  (struct foo (x))
  (struct bar foo ()))

(module second racket
  (require (submod ".." first))
  (provide (contract-out (struct foo ([x any/c])))
           (contract-out (struct (bar foo) ([x any/c])))))

(require 'second)
(provide (contract-out (struct (bar foo) ([x any/c]))))
```

Error (on 7.7 BC):
```
substring: starting index is out of range
  starting index: 24
  valid range: [0, 5]
  string: "foo-x"
```

**Comment by sorawee** [comment] 2020-06-27 06:42
Jeez.

Another problem:

```
#lang racket 

(struct foo (x))
(struct bar foo (x))
```

can't be `(provide (contract-out (struct (bar foo) ...)))`.

**Comment by sorawee** [comment] 2020-06-27 09:16
Also:

```
#lang racket

(module first racket
  (provide (contract-out (struct foo ([x any/c])))
           (contract-out (struct (bar foo) ([x any/c]))))
  (struct foo (x))
  (struct bar foo ()))

(require 'first)

(struct-copy bar (bar 1) [x #:parent foo 2])
```

fails with:

```
struct-copy: identifier not bound to a parent struct
  at: foo
  in: (struct-copy bar (bar 1) (x #:parent foo 2))
```

(Note: this also fails before #2700)

**Comment by sorawee** [comment] 2020-06-28 08:21
The bug reported by @camoy is fixed in #732, but that PR is not in a mergeable state anymore. #3267 is the first step to revive the PR.

**Comment by sorawee** [comment] 2020-06-28 08:23
Let me also separate the problems I found to another issues so that this issue can be closed once the fix lands.

**Comment by sorawee** [comment] 2020-06-29 12:20
Turns out the root cause of this problem is also what causes #3269. So while using the static field name information is the right way to do things and will seemingly fix this issue, it doesn't really eliminate the underlying bug. Fortunately, that bug is pretty easy to fix. I have a patch that I'm testing right now.

**Closed** 2020-06-30 00:35 UTC
