### ISSUE TITLE
A struct with prop:flat-contract and no custom writer crashes BC (And causes non-fatal errors on CS)

### ISSUE THREAD

**Issue by shawnw** [racket/racket#5003] opened 2024-05-29 00:52 UTC
The following example program:

```
#lang racket

(struct example (foo?)
  #:property prop:flat-contract
  (build-flat-contract-property
   #:name 'example-contract
   #:first-order (lambda (obj) (example-foo? obj))))

(example real?)
```

generates this output when run with Racket 8.13 CS:

```
application: not a procedure;
 expected a procedure that can be applied to arguments
  given: 'example-contract
  context...:
  ```

and eventually after a long pause causes Racket 8.13 BC to die with a SIGKILL, and on Racket 8.11 CS just prints `#<procedure:example>`. I don't have any older versions of BC installed to test them. Something done in the last couple of releases seems to have caused a regression in this situation, though.

**Comment by usaoc** [comment] 2024-05-29 03:01
Not a bug; `get-name` should be `(contract? . -> . any/c)`.

**Comment by rfindler** [comment] 2024-05-29 03:03
Perhaps the missing check should be considered a bug?

**Comment by shawnw** [comment] 2024-05-29 16:42
> Not a bug; `get-name` should be `(contract? . -> . any/c)`.

Not sure how you'd think something that crashes the Racket runtime just by trying to print a struct isn't a bug. Especially when it used to not do so.

what's `get-name`? Nothing relevant came up in a search.

**Comment by shawnw** [comment] 2024-05-29 16:44
Update: Racket 8.12 BC and CS both just print the semi-expected `#<procedure:example>` (I assume the contract property is what's making the printer treat the struct like it was a procedure). That narrows it down to something added for 8.13.

**Comment by shawnw** [comment] 2024-05-29 16:52
> The argument at the `#:name` position in `build-flat-contract-property` is named `get-name` in [the documentation](https://docs.racket-lang.org/reference/Building_New_Contract_Combinators.html#%28def._%28%28lib._racket%2Fcontract%2Fcombinator..rkt%29._build-flat-contract-property%29%29), and it's documented that it must be a function.
> 

... huh. I appear to have completely misunderstood `build-flat-contract-property` when I wrote the code causing the problem a few years ago. That makes the 8.13 CS error make a lot more sense. Still shouldn't be crashing BC.

**Comment by usaoc** [comment] 2024-05-30 03:56
The crash on BC is not ideal, but I think I know why that happens: the “not a procedure” error, on BC specifically, prints out the arguments, but we *are* printing one of the arguments (the contract itself)!  This makes it an infinite loop, which eventually crashes.  That’s why the context, if you get one at all, points to a repeated line of `/path/to/contract/private/prop.rkt:306:2`.

**Comment by sorawee** [comment] 2024-05-30 04:24
(Also FWIW, I think the change that causes the "regression" is https://github.com/racket/racket/commit/53669e95593d26ff2bf2275f57b3e4306d22b204, which explains why previous versions don't see the problem)

**Comment by rfindler** [comment] 2024-05-30 12:32
Thanks for sorting all this out! I've pushed what's likely the right fix.

**Comment by sorawee** [comment] 2024-06-01 05:11
Let me close this issue then

**Closed by sorawee** 2024-06-01 05:11 UTC
