### ISSUE TITLE
r6rs (exit #f) signals success

### ISSUE THREAD

**Issue by asebian** [racket/racket#4992] opened 2024-05-11 15:53 UTC
I came across a minor issue with the r6rs exit procedure:
A racket script calling `(exit #f)` terminates normally signalling success on some systems.
This does not comply with the behavior of `(exit)` and `(exit obj)` as described in R6RS Standard Libraries - Chapter 10: 

"Exits the running program and communicates an exit value to the operating system. If no argument is supplied, the exit procedure should communicate to the operating system that the program exited normally. If an argument is supplied, the exit procedure should translate the argument into an appropriate exit value for the operating system. **If obj is #f, the exit is assumed to be abnormal.**"

**What version of Racket are you using?**
```
bash$ racket --version
Welcome to Racket v8.2 [cs].
```
**What program did you run?**
```
bash$ cat false.rkt
#!/usr/bin/env racket

#!r6rs

(import (rnrs programs (6)))

(exit #f)
```
```
bash$ ./false.rkt; echo $?
0
```
**What should have happened?**
```
bash$ ./false.rkt; echo $?
1
```
because
```
bash$  type true false
true is a shell builtin
false is a shell builtin
bash$ true; echo $?
0
bash$ false; echo $?
1
```
**Please include any other relevant details**
```
bash$ uname -a
Linux TWR 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
bash$ cat /etc/issue
Ubuntu 22.04.4 LTS \n \l
bash$  cat /etc/debian_version
bookworm/sid
```
Whereas on Windows ...
```
CMD> ver
Microsoft Windows [Version 10.0.22631.3527]
CMD> racket --version
Welcome to Racket v8.12 [cs].
CMD> racket false.rkt
CMD> echo %ERRORLEVEL%
1
```

**Comment by jbclements** [comment] 2024-05-11 16:47
It looks to me like you're using version 8.2 in your first test. My test using v8.12 on debian 12.5 yields an output of 1:

```
clements@obama:/tmp$ cat > false.rkt
#!/usr/bin/env racket

#!r6rs

(import (rnrs programs (6)))

(exit #f)
clements@obama:/tmp$ chmod a+x false.rkt
clements@obama:/tmp$ ./false.rkt; echo $?
1
clements@obama:/tmp$ uname -a
Linux obama 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux
clements@obama:/tmp$ less /etc/debian_version 
clements@obama:/tmp$ cat /etc/debian_version 
12.5
clements@obama:/tmp$ 
```

Let me know if I'm misunderstanding something about your test!

**Comment by usaoc** [comment] 2024-05-12 04:42
Duplicate of racket/r6rs#9, fixed in racket/r6rs@f5e0ddb.  (Please report further R⁶RS issue there.  Can someone transfer this issue there also?)

**Comment by sorawee** [comment] 2024-05-12 04:54
Since it's a duplicate and also fixed, I'd rather just close it.

**Closed by sorawee** 2024-05-12 04:54 UTC

**Comment by asebian** [comment] 2024-05-12 20:23
Sorry for the fuzz.
I moved on to the next OS release. Problem solved.
