### ISSUE TITLE
A missing package in the catalog causes `raco pkg update -a` to fail

### ISSUE THREAD

**Issue by samth** [racket/racket#1272] opened 2016-03-01 22:21 UTC
If a package that's installed from a catalog now depends on something that's missing from the catalog, running `raco pkg update -a` will fail with the error:

```
raco pkg update: cannot find package on catalogs
  package: PACKAGE-NAME
```

This will also cause `make` to fail when it tries to update packages.

**Comment by mflatt** [comment] 2016-03-02 15:45
@samth Do you mean that the old version of the package depended on something that's no longer in the catalog, and the new version doesn't (and that should work)? Or that even a new version of the package, if any, depends on another package that can't be found (in which case I don't immediately see an alternative to failure)?

**Comment by samth** [comment] 2016-03-02 15:50
It appears that I misdiagnosed the error: it's actually that I had the `xdr` package installed from a catalog, and it's no longer available on any catalog, so the issue isn't a dependency.

I think in this case `raco pkg update -a` should just skip updating `xdr` and continue (otherwise it's harder to use and doesn't compose well with tools like `make`).

**Comment by mflatt** [comment] 2016-03-02 16:27
I'm reluctant to make `raco pkg update -a` always ignore catalog failures, but I think it could make sense to add a `--skip-on-catalog-fail` flag and use it in `make`.

**Comment by samth** [comment] 2016-03-02 16:34
That seems like a reasonable compromise.

**Comment by mflatt** [comment] 2016-03-03 12:58
I've half implemented this, and after thinking about it more, I don't think it would be a good idea to add `--skip-on-catalog-fail` to the makefile.

The problem is that there are many ways for things to go wrong, and quiet failure (even if some printout means that it's not entirely silent) will be a bad idea most of the time. Many bad states will be indistinguishable from a package name being not registered at a catalog; normally, automation built around package updating should fail if any of its service dependencies go wrong.

I think a more reliable approach would be a way to mark a package installation as "frozen". Operationally, updating would treat the installed checksum of a frozen package always as the current checksum for that package. If you want to have something installed by name that is not provided by the current set of catalogs, or if you want to install from a remote package source that will later go away, then you can switch the package to frozen mode.

Besides providing a solution to the immediate problem, I think the notion of a frozen package could be useful for other purposes. It's possible to implement freezing from the outside by updating a package installation to point to a local copy as its source, but adding specific support for freezing an installation looks easy, useful, and more clear to have as an explicit feature.

**Comment by samth** [comment] 2016-03-03 15:40
On the one hand, I agree with you that mostly-silent failure is a bad idea.

On the other hand, this is a failure in the default `make` target for Racket, which requires some non-trivial hacking (even if there's a way to mark a package as frozen) to fix. 

My opinion is still that updating arbitrary packages in the default `make` target is the wrong default, but given that it's the default, I think it should be more resistant to failure. If this was about `make update-all` then I'd agree entirely.

**Comment by mflatt** [comment] 2016-03-03 19:20
I understand your position that `make` would be better as an alias for `make as-is` instead of `make update-all`. I don't agree, but it seems like a reasonable position.

Given that `make` does mean `make update-all`, and given that we agree on mostly-silent failure as a bad idea for `make update-all`, it seems like we should agree that adding `--skip-on-catalog-fail` to `make` would be a bad idea.

It seems possible that there's a third default for `make` that you have in mind, but I don't see what that third point might mean in general. We seem to agree that "update unless there's a problem with the catalog" wouldn't be a good general meaning.

**Comment by samth** [comment] 2016-03-04 00:39
A few thoughts:

1. The default `make` target shouldn't put users in a position where they have to work hard to fix their system.
2. Silently (or almost-silently) erroring is a bad idea, unless someone asks for it explicitly. 

I don't, given those preferences and the current defaults, have a definitive better suggestion than the current defaults. 

Other possibilities (that I'm not really suggesting): prompt the user, skip the update step but run `raco setup`, maybe something else.

**Comment by mflatt** [comment] 2021-05-15 14:38
Ok to close? Having `make` act as `make update-all` is even more entrenched 5 years later, and while improvements to the package system are always possible, I don't have the sense that this kind of problem has been persistent.

**Comment by samth** [comment] 2021-05-15 15:33
I still think, after more years of experience here, that `raco pkg update -a` has too high a failure rate to be part of the default build. This issue probably isn't isn't the place to address that, though, so I'll close this.

**Closed** 2021-05-16 00:49 UTC
