### ISSUE TITLE
`raco demod` reports an error

### ISSUE THREAD

**Issue by Antigen-1** [racket/racket#4766] opened 2023-09-25 17:17 UTC
**What version of Racket are you using?**
8.10 [cs]

**What program did you run?**
`raco demod <my source code>`

**What should have happened?**
My code can be executed directly with `racket` so the compiler should have successfully compiled it.

**If you got an error message, please include it here.**
```
hash-set: contract violation
  expected: (and/c hash? immutable?)
  given: (reference-record '#hasheq() '#hasheq() #f)
  argument position: 1st
  other arguments...:
   'loc_3882
   #<local-variable>
  compilation context...:
   /home/hin/racket/collects/racket/contract/private/arrow-val-first.rkt
   /home/hin/racket/collects/racket/contract/private/case-arrow.rkt
   /home/hin/racket/collects/racket/contract/base.rkt
   /home/hin/racket/collects/racket/generic.rkt
   /home/hin/racket/collects/racket/stream.rkt
   /home/hin/repo/swapview/Racket_future/swapview.rkt
  context...:
   /home/hin/racket/collects/compiler/private/cm-minimal.rkt:686:0: compile-zo*
   /home/hin/racket/collects/compiler/private/cm-minimal.rkt:627:0: compile-zo*/cross-compile
   /home/hin/racket/collects/compiler/private/cm-minimal.rkt:452:15
   /home/hin/racket/collects/compiler/private/cm-minimal.rkt:441:12: build
   /home/hin/racket/collects/compiler/private/cm-minimal.rkt:412:0: maybe-compile-zo
   /home/hin/racket/collects/compiler/private/cm-minimal.rkt:210:0: compile-root
   /home/hin/racket/collects/compiler/private/cm-minimal.rkt:145:4: compilation-manager-load-handler
   /home/hin/racket/collects/compiler/private/cm-minimal.rkt:686:0: compile-zo*
   /home/hin/racket/collects/compiler/private/cm-minimal.rkt:627:0: compile-zo*/cross-compile
   /home/hin/racket/collects/compiler/private/cm-minimal.rkt:452:15
   /home/hin/racket/collects/compiler/private/cm-minimal.rkt:441:12: build
   /home/hin/racket/collects/compiler/private/cm-minimal.rkt:412:0: maybe-compile-zo
   /home/hin/racket/collects/compiler/private/cm-minimal.rkt:210:0: compile-root
   /home/hin/racket/collects/compiler/private/cm-minimal.rkt:145:4: compilation-manager-load-handler
   /home/hin/racket/collects/compiler/private/cm-minimal.rkt:686:0: compile-zo*
   /home/hin/racket/collects/compiler/private/cm-minimal.rkt:627:0: compile-zo*/cross-compile
   ...
```

**Please include any other relevant details**
```
uname -a
Linux hin-HLYL-WXX9 6.2.0-33-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 10:33:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

Besides, I use the `racket/future` library in my application.

**Comment by sorawee** [comment] 2023-09-25 17:29
Could you provide your code, or even better, a minimal code that provokes this issue?

**Comment by sorawee** [comment] 2023-11-17 14:41
I will close the issue since the problem is not reproducible. But feel free to reopen if you can trigger the issue again. Based on the error message I agree that something is off.

**Closed by sorawee** 2023-11-17 14:41 UTC
