### ISSUE TITLE
raco pkg show doesn't validate regexp arguments

### ISSUE THREAD

**Issue by takikawa** [racket/racket#1251] opened 2016-02-20 20:53 UTC
Here's an example that should produce a nicer error message:

```
$ raco pkg show --rx +
Installation-wide:
regexp: `+' follows nothing in pattern
  context...:
   /home/asumu/plt/racket-git/racket/collects/racket/private/list.rkt:103:2: memf
   /home/asumu/plt/racket-git/racket/collects/pkg/private/show.rkt:30:4: for-loop
   /home/asumu/plt/racket-git/racket/collects/pkg/private/show.rkt:13:0: pkg-show15
   /home/asumu/plt/racket-git/racket/collects/racket/contract/private/arrow-val-first.rkt:401:3
   /home/asumu/plt/racket-git/racket/collects/racket/file.rkt:378:8
   /home/asumu/plt/racket-git/racket/collects/racket/file.rkt:367:0: call-with-file-lock42
   /home/asumu/plt/racket-git/racket/collects/pkg/main.rkt:406:13: for-loop
   (submod /home/asumu/plt/racket-git/racket/collects/pkg/main.rkt main): [running body]
   /home/asumu/plt/racket-git/racket/collects/pkg/raco.rkt: [traversing imports]
```

**Comment by jeapostrophe** [comment] 2016-02-21 20:41
The error message says exactly what the problem is... the regexp you put in
had an error. What did you expect?

On Sat, Feb 20, 2016 at 3:53 PM, Asumu Takikawa <notifications@github.com>
wrote:

> Here's an example that should produce a nicer error message:
>
> $ raco pkg show --rx +
> Installation-wide:
> regexp: `+' follows nothing in pattern
>   context...:
>    /home/asumu/plt/racket-git/racket/collects/racket/private/list.rkt:103:2: memf
>    /home/asumu/plt/racket-git/racket/collects/pkg/private/show.rkt:30:4: for-loop
>    /home/asumu/plt/racket-git/racket/collects/pkg/private/show.rkt:13:0: pkg-show15
>    /home/asumu/plt/racket-git/racket/collects/racket/contract/private/arrow-val-first.rkt:401:3
>    /home/asumu/plt/racket-git/racket/collects/racket/file.rkt:378:8
>    /home/asumu/plt/racket-git/racket/collects/racket/file.rkt:367:0: call-with-file-lock42
>    /home/asumu/plt/racket-git/racket/collects/pkg/main.rkt:406:13: for-loop
>    (submod /home/asumu/plt/racket-git/racket/collects/pkg/main.rkt main): [running body]
>    /home/asumu/plt/racket-git/racket/collects/pkg/raco.rkt: [traversing imports]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/racket/racket/issues/1251>.
>



-- 
Jay McCarthy
Associate Professor
PLT @ CS @ UMass Lowell
http://jeapostrophe.github.io

           "Wherefore, be not weary in well-doing,
      for ye are laying the foundation of a great work.
And out of small things proceedeth that which is great."
                          - D&C 64:33

**Comment by samth** [comment] 2016-02-21 20:44
The explanation is good, but we shouldn't be reporting error messages from the internals of the implementation to the user.

**Comment by jeapostrophe** [comment] 2016-02-21 20:45
It's not the implementation. The error is with the regexp, which is what it
says

On Sun, Feb 21, 2016 at 3:44 PM, Sam Tobin-Hochstadt <
notifications@github.com> wrote:

> The explanation is good, but we shouldn't be reporting error messages from
> the internals of the implementation to the user.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/racket/racket/issues/1251#issuecomment-186911683>.
>



-- 
Jay McCarthy
Associate Professor
PLT @ CS @ UMass Lowell
http://jeapostrophe.github.io

           "Wherefore, be not weary in well-doing,
      for ye are laying the foundation of a great work.
And out of small things proceedeth that which is great."
                          - D&C 64:33

**Comment by jeapostrophe** [comment] 2016-02-21 20:46
Are you saying it should call `regexp` sooner and pass in the compiled
regexp?

On Sun, Feb 21, 2016 at 3:45 PM, Jay McCarthy <jay.mccarthy@gmail.com>
wrote:

> It's not the implementation. The error is with the regexp, which is what
> it says
>
> On Sun, Feb 21, 2016 at 3:44 PM, Sam Tobin-Hochstadt <
> notifications@github.com> wrote:
>
>> The explanation is good, but we shouldn't be reporting error messages
>> from the internals of the implementation to the user.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/racket/racket/issues/1251#issuecomment-186911683>.
>>
>
>
>
> --
> Jay McCarthy
> Associate Professor
> PLT @ CS @ UMass Lowell
> http://jeapostrophe.github.io
>
>            "Wherefore, be not weary in well-doing,
>       for ye are laying the foundation of a great work.
> And out of small things proceedeth that which is great."
>                           - D&C 64:33
>



-- 
Jay McCarthy
Associate Professor
PLT @ CS @ UMass Lowell
http://jeapostrophe.github.io

           "Wherefore, be not weary in well-doing,
      for ye are laying the foundation of a great work.
And out of small things proceedeth that which is great."
                          - D&C 64:33

**Comment by samth** [comment] 2016-02-21 20:52
No, I'm saying that it should check if the regexp is valid, and `raco pkg show` should produce the error.

A different way of putting it is that if `regexp` had a contract, the contract error would blame the `raco pkg show` implementation, and thus the `raco pkg show` implementation should be fixed.

**Closed** 2016-04-09 01:48 UTC
