### ISSUE TITLE
Error in Unit library if there is a circular dependency

### ISSUE THREAD

**Issue by LeifAndersen** [racket/racket#1324] opened 2016-05-06 22:17 UTC
If I try to run the following program (note the circular dependency):

```
#lang racket

(define-signature imp^
  (import1))

(define-signature exp^
  (export1))

(define-unit uni1@
  (import imp^)
  (export exp^)
  (define export1 import1))

(define-unit uni2@
  (import exp^)
  (export imp^)
  (define import1 export1))

(define-compound-unit/infer uni1+uni2@
  (import)
  (export imp^ exp^)
  (link uni1@ uni2@))

(define-values/invoke-unit/infer uni1+uni2@)
```

I get the following error:

```
. . racket/racket/collects/racket/unit.rkt:1038:58: import1: undefined;
 cannot use before initialization
```

Which makes sense given Claire's letrec pass. However, it seems to me that we should either document this and change the error message, or switch too using something else besides `letrecvalues+syntaxes`. As right now it looks like a bug in our implementation.

**Comment by mflatt** [comment] 2016-05-09 17:29
I think you mean to point out that the source location in the error message is for `racket/unit`, as opposed to the source program. I agree that should be fixed, although I'm not certain offhand how much it's about errortrace and how much the problem is with `racket/unit`.

(I was confused by the mention of the letrec pass and `letrec-values+syntaxes`, neither of which are directly relevant here. The `unit` form implements its own checking for use-before-defined.)

**Closed** 2021-04-28 14:36 UTC
