### ISSUE TITLE
`raco pkg install` ssl requested protocol not supported error

### ISSUE THREAD

**Issue by sudo-panda** [racket/racket#4306] opened 2022-06-16 16:01 UTC
**What version of Racket are you using?**
8.5+ppa1-1~jammy1

**What program did you run?**
`raco pkg install` (`raco pkg install --skip-installed --auto generic-flonum` in my case)

**What should have happened?**
Should execute successfully.

**If you got an error message, please include it here.**
It fails with error:
```
Resolving "generic-flonum" via https://download.racket-lang.org/releases/8.5/catalog/
ssl-make-client-context: requested protocol not supported;
 SSL not available; check `ssl-load-fail-reason'
  requested: 'auto
  context...:
   /usr/share/racket/collects/openssl/mzssl.rkt:687:0: encrypt->method
   /usr/share/racket/collects/openssl/mzssl.rkt:762:0: make-raw-context
   /usr/share/racket/collects/openssl/mzssl.rkt:751:0: make-context
   /usr/share/racket/collects/openssl/mzssl.rkt:779:0: ssl-make-client-context
   /usr/share/racket/collects/openssl/mzssl.rkt:1109:0: ssl-secure-client-context
   /usr/share/racket/collects/openssl/mzssl.rkt:794:0: get-context
   /usr/share/racket/collects/openssl/mzssl.rkt:628:18
   /usr/share/racket/collects/ffi/unsafe/atomic.rkt:73:13
   /usr/share/racket/collects/openssl/mzssl.rkt:1638:0: wrap-ports
   /usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt:555:3
   /usr/share/racket/collects/net/http-client.rkt:67:0: http-conn-open!
   /usr/share/racket/collects/net/http-client.rkt:274:0: http-conn-open
   /usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt:555:3
   /usr/share/racket/collects/net/url.rkt:202:0: http://getpost-impure-port
   /usr/share/racket/collects/net/url.rkt:305:0: get-pure-port/headers
   /usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt:555:3
   ...
```

**Please include any other relevant details**
OS: Pop_OS! 22.04
openssl: 3.0.2-0ubuntu1.2

**Possible Fix**
Install `libssl-dev` package.

**Comment by Kraks** [comment] 2022-06-19 04:30
I had the same issue after installing ubuntu 22.04. Try to install `libssl-dev` should solve the problem:
```
sudo apt install libssl-dev
```

**Comment by LiberalArtist** [comment] 2022-06-30 00:23
I've confirmed that this has been fixed with the latest snapshot. In a fresh Ubuntu 22.04 container **without** the `libssl-dev` package installed:
```
root@912c45c2a7c6:/# /usr/local/racket/bin/racket 
Welcome to Racket v8.5 [cs].
> (require openssl)
> ssl-load-fail-reason
"ffi-lib: could not load foreign library\n  path: libcrypto.so\n  system error: libcrypto.so: cannot open shared object file: No such file or directory"
> 
root@912c45c2a7c6:/# /usr/local/racket-8.5.0.8/bin/racket 
Welcome to Racket v8.5.0.8 [cs].
> (require openssl)
> ssl-load-fail-reason
#f
> 
```
The fix will be included in the upcoming Racket 8.6 release, and you should be able to remove the `libssl-dev` package then.

**Comment by LiberalArtist** [comment] 2022-06-30 00:24
(I wonder if we could improve the error message in the original post, though.)

**Comment by samth** [comment] 2022-09-01 00:38
Should this be closed now?

**Comment by 1216892614** [comment] 2023-05-07 06:44
I got error like this when I just try to install on my WSL2

```sh
> raco pkg install racket-langserver
Resolving "racket-langserver" via https://download.racket-lang.org/releases/8.2/catalog/
net/url: "ALL_PROXY" contained invalid proxy URL format: "socks5://172.22.192.1:7890"
SSL_get_peer_certificate: implementation not found; arguments: #<cpointer>
  context...:
   /usr/share/racket/collects/ffi/unsafe/alloc.rkt:80:14
   /usr/share/racket/collects/ffi/unsafe/atomic.rkt:73:13
   /usr/share/racket/collects/openssl/mzssl.rkt:1590:0: wrap-ports
   /usr/share/racket/collects/net/http-client.rkt:280:0: http-conn-CONNECT-tunnel
   /usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt:555:3
   /usr/share/racket/collects/net/url.rkt:167:0: make-ports
   /usr/share/racket/collects/net/url.rkt:202:0: http://getpost-impure-port
   /usr/share/racket/collects/net/url.rkt:305:0: get-pure-port/headers
   /usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt:555:3
   /usr/share/racket/collects/pkg/private/network.rkt:59:3
   /usr/share/racket/collects/pkg/private/catalog.rkt:218:0: read-from-server
   /usr/share/racket/collects/pkg/private/catalog.rkt:135:2: lookup-normally
   /usr/share/racket/collects/pkg/private/prefetch.rkt:129:4
   /usr/share/racket/collects/pkg/private/prefetch.rkt:128:2
   /usr/share/racket/collects/pkg/private/catalog.rkt:132:0: package-catalog-lookup
   /usr/share/racket/collects/pkg/private/catalog.rkt:200:0: package-catalog-lookup-source
   ...
```

Im using clash as proxy, and theres nothing wrong with my network.

**Comment by jbclements** [comment] 2023-05-07 17:24
@1216892614 , is this report related to the original issue? I'm confused.

**Comment by LiberalArtist** [comment] 2023-05-07 20:38
ISTM the original issue was a failure to `dlopen` the library, but the new one is from `dlsym` failing to find a function (suggesting that `dlopen` succeeded).

**Comment by 1216892614** [comment] 2023-05-08 05:09
> @1216892614 , is this report related to the original issue? I'm confused.

I thought both of them are same, but they are not.

I fix this problem, this happend just because apt install raco in `/usr`, any raco command should only work fine in root.

So I just reinstall racket with shell script.

**Comment by jbclements** [comment] 2023-05-08 05:47
Glad to hear it! I'm going to close this issue, let me know if you think this is mistaken.

**Closed by jbclements** 2023-05-08 05:47 UTC

**Comment by LiberalArtist** [comment] 2023-05-09 17:14
I agree that the original report should be closed and that the new issue seems unrelated, but:

> > @1216892614 , is this report related to the original issue? I'm confused.
> 
> I thought both of them are same, but they are not.
> 
> I fix this problem, this happend just because apt install raco in `/usr`, any raco command should only work fine in root.
> 
> So I just reinstall racket with shell script.

Racket installed via `apt` definitely *is* supposed to have a working `raco`, including for non-root users to install additional Racket packages in user scope. If that didn't work for you, please do report a bug! It could well be a different symptom of the same underlying change that exposed this bug: distros are transitioning (indeed, largely have transitioned) to OpenSSL 3, and Racket supports OpenSSL 3 in addition to the 1.1 series, but bugs in Racket, in downstream packaging, or both could result in Racket not finding a good OpenSSL and perhaps finding a bad one instead. It would help to know what distro you're using under WSL and what dpkg repository you're getting Racket from (i.e. are you using a PPA?). I particularly encourage you to report if you're using Debian Bookworm so we can try to get a fix in before the release.

There are also lots of confusing error messages in this thread that could certainly be improved.

**Comment by myfreess** [comment] 2023-07-10 06:48
@1216892614 weird, export all_proxy="http://127.0.0.1:7890" works in my machine, seems like the net/url library cant handle socks5 url.
